import type { InterviewQuestion } from "./questions";

export type InterviewAnswer = {
  short: string;
  points: string[];
  example: string;
  caveat: string;
};

type Rule = {
  match: RegExp;
  short: string;
  points?: string[];
  example?: string;
  caveat?: string;
};

const rules: Rule[] = [
  { match: /семантическ/i, short: "Семантическая разметка описывает смысл контента подходящими HTML-элементами, а не только его внешний вид.", points: ["Она улучшает accessibility tree, навигацию скринридера, SEO и поддержку кода.", "Сначала выбирают нативный элемент с нужным поведением; div используют, когда подходящей семантики нет."], example: "Для основной навигации: nav со списком ссылок; для самостоятельной публикации: article.", caveat: "Сам тег не делает интерфейс доступным: остаются контраст, фокус, клавиатура и понятные подписи." },
  { match: /block, inline|inline-block/i, short: "Block обычно занимает доступную ширину и начинает новую строку; inline участвует в строковом потоке; inline-block остаётся в строке, но принимает размеры блока.", example: "span — inline, div — block, кнопка с заданной шириной может быть inline-block.", caveat: "Точное поведение зависит от formatting context и значения display, а не от имени тега." },
  { match: /button, а когда ссылку|button.*ссылк/i, short: "Ссылка выполняет навигацию и имеет href; button запускает действие в текущем интерфейсе.", points: ["Правильный элемент бесплатно даёт клавиатурное поведение, роль и ожидаемую семантику."], example: "«Открыть профиль» — ссылка; «Сохранить изменения» — кнопка.", caveat: "Не превращайте div в кнопку и не используйте href='#' для действия." },
  { match: /section отличается/i, short: "main содержит основное уникальное содержимое; article — самостоятельный материал; section — тематический раздел обычно с заголовком; aside — связанное вторичное содержимое; div — контейнер без семантики.", caveat: "Не заменяйте каждый div на section: section должен выражать реальный раздел документа." },
  { match: /doctype|quirks mode/i, short: "<!doctype html> включает стандартный режим рендеринга. Без него браузер может перейти в quirks mode и имитировать старые несовместимые правила.", example: "В quirks mode иначе считается box model и могут отличаться layout-алгоритмы.", caveat: "Современный doctype не указывает версию HTML." },
  { match: /label.*input|placeholder.*label/i, short: "label связывают с input через for/id или вложением input. Он создаёт accessible name и увеличивает кликабельную область.", caveat: "Placeholder исчезает после ввода, имеет слабый контраст и не является постоянным названием поля." },
  { match: /defer, async/i, short: "Обычный script блокирует парсинг. async загружается параллельно и выполняется сразу после загрузки без сохранения порядка. defer загружается параллельно и выполняется после парсинга в порядке документа.", caveat: "ES-модули по умолчанию ведут себя близко к defer, но их граф зависимостей загружается отдельно." },
  { match: /progressive enhancement/i, short: "Progressive enhancement начинает с работающей HTML-основы и добавляет CSS/JavaScript как улучшение.", example: "Форма отправляется на сервер без JS, а с JS получает inline-валидацию и optimistic UI.", caveat: "Не каждый продукт обязан полностью работать без JS, но критические потоки должны деградировать предсказуемо." },
  { match: /srcset|picture/i, short: "srcset перечисляет варианты изображения, sizes описывает ожидаемую ширину, а браузер выбирает ресурс с учётом viewport и DPR. picture позволяет art direction и разные форматы.", caveat: "Неверный sizes часто заставляет браузер скачать слишком большой файл." },
  { match: /accessibility tree/i, short: "Accessibility tree — представление интерфейса для assistive technologies: роли, имена, состояния и связи, вычисленные из DOM, CSS и ARIA.", caveat: "Элементы с display:none обычно исключаются; визуальный текст и accessible name могут различаться." },
  { match: /tabindex=0|tabindex.*-1/i, short: "tabindex=0 добавляет элемент в естественный порядок фокуса; -1 позволяет сфокусировать его программно, но исключает из Tab-навигации.", caveat: "Положительные значения создают искусственный порядок, который трудно поддерживать и который расходится с DOM." },
  { match: /accessible name/i, short: "Accessible name — имя элемента, объявляемое скринридером. Оно вычисляется из label, текста элемента, aria-labelledby, aria-label и других источников по алгоритму приоритетов.", caveat: "Имя должно соответствовать видимой подписи, иначе голосовое управление становится непредсказуемым." },
  { match: /aria-label.*aria-labelledby|aria-describedby/i, short: "aria-label задаёт имя строкой; aria-labelledby ссылается на видимый элемент с именем; aria-describedby добавляет отдельное описание.", caveat: "ARIA меняет семантику для accessibility API, но не добавляет клавиатурное поведение." },
  { match: /специфичност/i, short: "Специфичность сравнивается по группам: inline styles; ID; классы/атрибуты/pseudo-classes; элементы/pseudo-elements. Побеждает первое различающееся большее значение.", points: ["До специфичности учитываются origin, importance и cascade layers; при равенстве побеждает более позднее правило."], caveat: "!important усложняет каскад; лучше управлять слоями и структурой селекторов." },
  { match: /box model|box-sizing/i, short: "Box model состоит из content, padding, border и margin. При content-box width задаёт content; при border-box в width уже входят padding и border.", caveat: "Margin не входит в физический размер border box." },
  { match: /схлопываются.*margin/i, short: "Вертикальные margin соседних block-элементов в обычном потоке могут объединиться до одного значения.", points: ["Схлопывание прекращают новый BFC, border/padding между элементами, flex/grid layout и absolute positioning."], caveat: "Горизонтальные margin не схлопываются." },
  { match: /stacking context/i, short: "Stacking context — независимый слой упорядочивания по оси z. Его создают, среди прочего, positioned element с z-index, opacity<1, transform, filter и isolation:isolate.", caveat: "Дочерний элемент не может своим большим z-index выйти выше соседнего stacking context родителя." },
  { match: /z-index.*не работает/i, short: "z-index сравнивается внутри текущего stacking context и применим не ко всем layout-ситуациям одинаково. Часто проблема в том, что родитель создал отдельный контекст.", example: "z-index:9999 у модального окна не перекроет header, если родитель модалки находится в нижнем stacking context.", caveat: "Ищите ближайшего предка, создающего stacking context, а не увеличивайте число." },
  { match: /Flexbox.*Grid|Grid.*Flexbox/i, short: "Flexbox оптимален для одномерного распределения по строке или колонке; Grid — для двумерной сетки с одновременным контролем строк и столбцов.", example: "Навигация — Flexbox; сетка карточек с выравниванием — Grid.", caveat: "Они дополняют друг друга и часто используются вместе." },
  { match: /min-width: 0/i, short: "У flex-item значение min-width:auto обычно не позволяет стать уже intrinsic-размера содержимого. min-width:0 разрешает сжатие и делает ellipsis рабочим.", caveat: "Альтернатива overflow:hidden также меняет automatic minimum size, но добавляет другое поведение overflow." },
  { match: /layout, paint.*composite|layout.*paint/i, short: "Layout вычисляет геометрию, paint рисует пиксели в слоях, composite собирает слои на экране. Изменения geometry обычно дороже изменений только compositor-свойств.", example: "Анимация transform/opacity часто не требует layout и paint.", caveat: "Создание множества compositor layers расходует память GPU." },
  { match: /will-change/i, short: "will-change заранее сообщает браузеру о вероятном изменении и может подготовить отдельный слой или оптимизацию.", caveat: "Постоянное применение к множеству элементов увеличивает память и иногда ухудшает производительность; включайте незадолго до изменения." },
  { match: /CSS Modules.*CSS-in-JS|utility-first/i, short: "CSS Modules дают локальные имена классов; CSS-in-JS связывает стили с JavaScript и может иметь runtime/SSR-стоимость; utility-first собирает интерфейс из малых предопределённых классов.", caveat: "Выбор зависит от design system, SSR, динамических стилей и командных соглашений, а не от моды." },
  { match: /@layer/i, short: "@layer задаёт явный порядок групп правил. Правило в более позднем слое побеждает правило из раннего слоя независимо от специфичности внутри этих слоёв.", caveat: "Unlayered author styles имеют приоритет над обычными layered styles." },
  { match: /типы данных.*JavaScript/i, short: "Примитивы: string, number, bigint, boolean, undefined, symbol и null. Отдельный непримитивный тип — object; функции являются вызываемыми объектами.", caveat: "typeof имеет исторические особенности: typeof null === 'object'." },
  { match: /typeof null/i, short: "Это историческая ошибка ранней реализации JavaScript: null кодировался похожим на объект значением. Поведение сохранено ради обратной совместимости.", example: "Проверяйте value === null, а не typeof value.", caveat: "Изменить результат нельзя без поломки существующего веба." },
  { match: /== и ===|===.*==/i, short: "=== сравнивает без преобразования типов; == применяет алгоритм абстрактного равенства и может преобразовать операнды.", example: "0 == false истинно, а 0 === false ложно.", caveat: "Обычно используют ===; осознанный value == null удобен для одновременной проверки null и undefined." },
  { match: /falsy/i, short: "Falsy: false, 0, -0, 0n, пустая строка, null, undefined и NaN. Все объекты, включая [] и {}, truthy.", caveat: "Проверка if(!value) смешивает отсутствие значения с корректными 0, false и пустой строкой." },
  { match: /null.*undefined/i, short: "undefined обычно означает «значение не задано», null — явное «значения нет». Оба nullish, но это разные значения и типы.", caveat: "Согласуйте один способ представления отсутствия данных в API и доменной модели." },
  { match: /NaN.*самому себе/i, short: "NaN по IEEE 754 не равен ничему, включая себя. Надёжная проверка — Number.isNaN(value).", caveat: "Глобальный isNaN сначала преобразует аргумент и может дать неожиданный результат." },
  { match: /var.*let.*const/i, short: "var имеет function scope, допускает повторное объявление и инициализируется undefined при hoisting. let/const имеют block scope и находятся в TDZ; const запрещает переназначение binding.", caveat: "const не делает объект неизменяемым." },
  { match: /hoisting|temporal dead zone/i, short: "Объявления регистрируются до выполнения области. var доступен как undefined, function declaration — как функция, а let/const существуют, но недоступны до строки инициализации: это TDZ.", caveat: "Hoisting — модель поведения, а не буквальное перемещение строк." },
  { match: /замыкание|closure/i, short: "Замыкание — функция вместе со ссылками на лексическое окружение, где она была создана. Оно позволяет сохранять состояние между вызовами.", example: "Фабрика createCounter возвращает функцию, которая читает и изменяет закрытую переменную count.", caveat: "Замыкание может удерживать большие объекты и стать причиной утечки." },
  { match: /значение this|определяется.*this/i, short: "this определяется способом вызова: new binding, явный call/apply/bind, method call или default binding. Стрелка не создаёт this и берёт его лексически.", caveat: "Передача метода как callback обычно теряет объект-получатель." },
  { match: /стрелочная функция/i, short: "Стрелка лексически захватывает this/arguments, не имеет prototype и не вызывается с new. Обычная функция получает this из call-site.", caveat: "Стрелка удобна для callback, но обычно не подходит как метод, которому нужен динамический this." },
  { match: /call, apply.*bind/i, short: "call вызывает функцию с this и отдельными аргументами; apply — с массивоподобным набором; bind возвращает новую функцию с закреплённым this и начальными аргументами.", caveat: "bind создаёт новый объект функции, что важно при add/removeEventListener." },
  { match: /цепочк.*прототип|prototype chain/i, short: "При чтении свойства движок сначала проверяет сам объект, затем его [[Prototype]] и так далее до null. Запись обычно создаёт собственное свойство.", caveat: "Глубокие цепочки и изменение прототипов во время работы ухудшают предсказуемость и оптимизацию." },
  { match: /spread.*глубок/i, short: "Object/array spread копирует только верхний уровень. Вложенные объекты остаются теми же ссылками.", example: "const b={...a}; b.user===a.user будет true.", caveat: "Для поддерживаемых данных используйте structuredClone; для доменных моделей часто лучше явное копирование." },
  { match: /Map.*обычного объекта/i, short: "Map принимает ключи любого типа, сохраняет порядок вставки, имеет size и удобную итерацию. Object прежде всего моделирует запись со строковыми/symbol ключами и прототипом.", caveat: "Map не сериализуется JSON.stringify напрямую." },
  { match: /Set, WeakMap.*WeakSet/i, short: "Set хранит уникальные значения. WeakMap/WeakSet держат объекты слабо и не мешают GC; поэтому они не перечисляются.", example: "WeakMap подходит для метаданных, время жизни которых совпадает с объектом-ключом.", caveat: "Weak-коллекции не подходят, если требуется итерация или размер." },
  { match: /optional chaining|nullish coalescing/i, short: "?. прекращает цепочку только при null/undefined. ?? берёт fallback только для null/undefined, сохраняя 0, false и пустую строку.", caveat: "Не скрывайте ?. ошибки там, где объект обязан существовать по инварианту." },
  { match: /for\.\.\.in.*for\.\.\.of/i, short: "for...in перебирает enumerable строковые ключи, включая унаследованные; for...of читает значения iterable по iterator protocol.", caveat: "Для массива обычно нужен for...of, entries или методы массива, а не for...in." },
  { match: /execution context/i, short: "Execution context хранит lexical/variable environment, this binding и служебное состояние выполняемого кода. Контексты образуют call stack.", caveat: "Глобальный, функциональный и eval-контексты создаются в разные моменты." },
  { match: /garbage collector|достижимости/i, short: "GC начинает с корней и помечает достижимые объекты; недостижимые освобождаются. Современные движки используют поколенческие и инкрементальные оптимизации.", caveat: "GC не освобождает логически ненужный объект, пока на него остаётся достижимая ссылка." },
  { match: /утечки памяти/i, short: "Частые утечки: неочищенные listeners/таймеры/подписки, глобальные кэши без лимита, detached DOM, замыкания и незавершённые async-операции.", points: ["Ищут рост heap между одинаковыми сценариями, сравнивают snapshots и inspect retaining paths."], caveat: "Большой heap не обязательно утечка; важен устойчивый рост после GC." },
  { match: /iterator protocol|iterable protocol/i, short: "Iterable имеет метод Symbol.iterator, возвращающий iterator. Iterator имеет next(), который возвращает {value, done}.", example: "Array, Map и string iterable, поэтому работают с for...of и spread.", caveat: "Iterator может быть одноразовым, а iterable — создавать новый iterator каждый раз." },
  { match: /generator/i, short: "Generator function возвращает iterator и приостанавливается на yield, сохраняя execution state. next(value) продолжает выполнение.", caveat: "Генераторы удобны для ленивых последовательностей, но async streams часто лучше моделировать async iterator." },
  { match: /Proxy.*Reflect/i, short: "Proxy перехватывает фундаментальные операции объекта через traps; Reflect предоставляет соответствующие операции с корректной семантикой по умолчанию.", caveat: "Proxy обязан соблюдать invariants, медленнее прямого доступа и не перехватывает внутренние slots некоторых встроенных объектов без обвязки." },
  { match: /ES Modules.*live bindings/i, short: "ESM статически анализируется; imports являются live read-only bindings на exports, а не копиями значений. Граф модулей связывается до выполнения.", caveat: "Циклические зависимости допустимы, но доступ до инициализации export может попасть в TDZ." },
  { match: /CommonJS.*ESM/i, short: "CommonJS загружается через require синхронно и экспортирует объект; ESM имеет статический граф, live bindings, async loading и лучше поддерживает tree shaking.", caveat: "Interop default/named exports зависит от runtime и bundler." },
  { match: /tree shaking/i, short: "Tree shaking удаляет недостижимые exports на основе статического ESM-графа и информации о side effects.", caveat: "Динамический require, побочные эффекты на уровне модуля и неверный sideEffects в package.json мешают или ломают оптимизацию." },
  { match: /structuredClone/i, short: "structuredClone глубоко копирует большинство structured-cloneable значений, поддерживает циклы и transferable objects.", caveat: "Он не клонирует функции, DOM-узлы и некоторые объекты с внутренним состоянием; пользовательские prototypes обычно не сохраняются как класс." },
  { match: /debounce.*throttle/i, short: "Debounce выполняет действие после паузы; throttle ограничивает частоту во время непрерывного потока.", example: "Поиск по вводу — debounce; обработка scroll/resize — throttle.", caveat: "Нужно определить leading/trailing поведение и предоставить cancel при размонтировании." },
  { match: /call stack.*task queue|microtask queue/i, short: "Event loop выполняет одну task, затем полностью очищает очередь microtasks и после этого браузер может обновить rendering.", example: "Promise.then и queueMicrotask выполнятся раньше setTimeout(0), запланированного в той же task.", caveat: "Бесконечная генерация microtasks вызывает starvation и не даёт браузеру отрисовать кадр." },
  { match: /Promise\.all.*allSettled|race.*any/i, short: "all ждёт все и отклоняется по первой ошибке; allSettled возвращает каждый результат; race берёт первое settled; any — первое fulfilled и иначе AggregateError.", caveat: "Отклонение combinator не отменяет уже запущенные операции — для отмены нужен AbortSignal." },
  { match: /async\/await.*под капотом/i, short: "async-функция всегда возвращает Promise. await приостанавливает её продолжение и ставит продолжение как microtask после settlement ожидаемого thenable.", caveat: "Последовательные await могут создать waterfall; независимые операции запускайте до ожидания." },
  { match: /AbortController/i, short: "AbortController создаёт signal; его передают fetch и другим поддерживающим API. abort() переводит signal в aborted и fetch отклоняется AbortError.", caveat: "Отмена fetch не откатывает действие, уже выполненное сервером." },
  { match: /race condition.*поиск/i, short: "Каждому запросу назначают версию или отменяют предыдущий AbortController. Результат применяется только если он относится к последнему актуальному запросу.", caveat: "Debounce уменьшает число запросов, но сам по себе не устраняет гонку ответов." },
  { match: /exponential backoff/i, short: "После временной ошибки задержку увеличивают экспоненциально и добавляют случайный jitter, чтобы клиенты не повторяли запрос одновременно.", caveat: "Не ретраят неидемпотентные операции без idempotency key и постоянные 4xx-ошибки." },
  { match: /Web Worker.*Service Worker/i, short: "Web Worker выполняет вычисления вне main thread и живёт вместе со страницей. Service Worker — origin-scoped proxy событий fetch/push, независимый от конкретной вкладки.", caveat: "Оба не имеют прямого доступа к DOM." },
  { match: /структурная типизация/i, short: "Совместимость TypeScript определяется формой значения: если объект содержит необходимые поля подходящих типов, имя объявления не важно.", caveat: "Это удобно для composition, но не создаёт runtime-гарантий и иногда требует branded types для номинальных различий." },
  { match: /interface.*type alias/i, short: "Оба описывают object shape. Interface поддерживает declaration merging и удобное extends; type умеет unions, primitives, tuples и произвольные type expressions.", caveat: "Для обычной объектной модели выбор чаще вопрос соглашения, а не производительности." },
  { match: /any.*unknown.*never/i, short: "any отключает проверку; unknown требует narrowing перед использованием; never означает невозможное значение или недостижимую ветвь.", caveat: "На границе недоверенных данных используйте unknown плюс runtime validation, а не any." },
  { match: /discriminated union/i, short: "Это union объектов с общим literal-полем-дискриминантом. Проверка поля сужает тип до конкретного варианта.", example: "type Result={status:'ok';data:T}|{status:'error';error:Error}.", caveat: "Exhaustive switch с never помогает обнаружить добавленный, но необработанный вариант." },
  { match: /satisfies/i, short: "satisfies проверяет совместимость выражения с типом, сохраняя более точный выведенный тип самого выражения.", caveat: "Он не преобразует значение и не выполняет runtime-проверку." },
  { match: /generic/i, short: "Generic связывает типы входов и выходов параметром, сохраняя информацию о конкретном типе вызывающей стороны.", example: "function first<T>(items:T[]):T|undefined.", caveat: "Generic полезен, когда тип действительно участвует в нескольких позициях; одноразовый T часто лишний." },
  { match: /conditional types/i, short: "Conditional type выбирает ветвь по assignability: T extends U ? X : Y. С naked type parameter он распределяется по union.", caveat: "Оберните T в tuple — [T] extends [U] — чтобы отключить distributivity." },
  { match: /mapped types/i, short: "Mapped type перебирает ключи union, обычно keyof T, и строит новые свойства, меняя тип или модификаторы readonly/optional.", example: "type Partial<T> = {[K in keyof T]?: T[K]}.", caveat: "Слишком сложные рекурсивные mapped types ухудшают сообщения об ошибках и скорость compiler." },
  { match: /variance|covariance|contravariance/i, short: "Variance описывает, как совместимость T влияет на совместимость Container<T>. Producer обычно covariant, consumer function parameter — contravariant, mutable container часто invariant.", caveat: "В TypeScript variance выводится структурно и имеет несколько pragmatic исключений ради совместимости." },
  { match: /runtime.*TypeScript|данным нельзя доверять|runtime-схем/i, short: "Типы TypeScript стираются при компиляции, поэтому внешние данные принимают как unknown и проверяют runtime-схемой или явными guards.", caveat: "Type assertion лишь заставляет compiler поверить разработчику и не защищает production." },
  { match: /декларативн/i, short: "React-компонент описывает, какой UI должен соответствовать текущим props/state; React решает, какие DOM-изменения применить.", caveat: "Императивная работа с DOM допустима на границах через refs, но не должна конкурировать с React за те же узлы." },
  { match: /props.*state/i, short: "Props приходят от родителя и считаются read-only; state принадлежит экземпляру позиции компонента и меняется через setter, вызывая новый render.", caveat: "Не копируйте props в state без причины: появляются две конкурирующие истины." },
  { match: /render.*commit/i, short: "На render-фазе React вызывает компоненты и вычисляет следующее дерево; на commit-фазе применяет DOM-изменения, refs и эффекты.", caveat: "Render может быть прерван или повторён, поэтому обязан оставаться чистым." },
  { match: /reconciliation/i, short: "Reconciliation сопоставляет прошлое и новое React-дерево по типу, позиции и key, решая, что сохранить, обновить или размонтировать.", caveat: "Смена type или key сбрасывает состояние subtree." },
  { match: /стабильные keys|индекс массива.*key/i, short: "Key задаёт идентичность элемента среди siblings. Стабильный ID позволяет React правильно сохранить state при вставке, удалении и reorder.", caveat: "Индекс безопасен только для действительно статичного списка без reorder и локального состояния." },
  { match: /мутировать state/i, short: "React определяет изменение по новым значениям/ссылкам и ожидает snapshot-модель state. Мутация старого объекта ломает сравнение, историю и concurrent rendering.", example: "setUser({...user,name:'Ann'}), а не user.name='Ann'.", caveat: "Локальная мутация нового объекта до передачи в state безопасна." },
  { match: /batching/i, short: "React группирует несколько state updates в один render/commit, чтобы избежать промежуточных состояний и лишней работы.", caveat: "Если новое значение зависит от предыдущего, используйте functional updater." },
  { match: /controlled.*uncontrolled/i, short: "Controlled input получает value из React state и сообщает изменения; uncontrolled хранит текущее значение в DOM и читается через ref/FormData.", caveat: "Не переключайте один input между controlled и uncontrolled во время жизни." },
  { match: /Context/i, short: "Context передаёт значение через дерево без prop drilling. Provider update перерендеривает потребителей, читающих этот context.", caveat: "Context удобен для зависимостей и редко меняющихся значений, но не заменяет автоматически селективный state store." },
  { match: /useRef/i, short: "useRef возвращает стабильный объект {current}. Изменение current сохраняется между renders, но не планирует новый render.", example: "DOM ref, timer ID или последнее значение для внешнего callback.", caveat: "Не читайте и не меняйте ref во время render, кроме предсказуемой ленивой инициализации." },
  { match: /useEffect.*не нужен/i, short: "Effect нужен для синхронизации с внешней системой. Вычисление derived data, обработка user event и сброс state по key обычно делаются без effect.", caveat: "Effect, который сразу setState на основе props, создаёт лишний render и риск рассинхронизации." },
  { match: /stale closure/i, short: "Callback замыкает значения конкретного render. Если он выполняется позже, внутри могут оказаться устаревшие props/state.", caveat: "Исправления: корректные dependencies, functional updater, перенос логики в event или ref для действительно не-реактивного чтения." },
  { match: /Strict Mode.*дважды/i, short: "В development Strict Mode намеренно повторяет некоторые render/effect циклы, чтобы выявить нечистый render и отсутствующий cleanup.", caveat: "Production не делает дополнительный цикл; исправлять нужно идемпотентность и cleanup, а не отключать проверку." },
  { match: /useEffect.*useLayoutEffect/i, short: "useEffect запускается после paint; useLayoutEffect — синхронно после DOM commit до paint и может измерить layout без мерцания.", caveat: "useLayoutEffect блокирует paint, поэтому используйте только для измерения/синхронной визуальной коррекции." },
  { match: /useMemo|useCallback|React\.memo/i, short: "useMemo кэширует вычисленное значение, useCallback — функцию, React.memo может пропустить render при равных props. Это оптимизации, не семантика.", caveat: "Стоимость сравнения и усложнение могут быть выше сэкономленного render; сначала измеряйте Profiler." },
  { match: /Fiber/i, short: "Fiber представляет React-работу как связные units, позволяя приоритизировать, приостанавливать, продолжать или отменять render до commit.", caveat: "Commit остаётся синхронным; concurrent rendering не означает параллельное изменение DOM." },
  { match: /useTransition|useDeferredValue|transition update/i, short: "Transition помечает обновление как non-urgent и допускает прерывание; useDeferredValue даёт отложенную версию значения для тяжёлого subtree.", caveat: "Они не делают вычисление быстрее и не подходят для самого controlled input value." },
  { match: /Suspense/i, short: "Suspense показывает fallback, когда совместимый источник данных или lazy component приостанавливает subtree; после готовности React повторяет render.", caveat: "Обычный fetch в useEffect не интегрируется с Suspense автоматически; boundaries нужно размещать по UX loading states." },
  { match: /hydration mismatch/i, short: "Hydration связывает клиентский React с серверным HTML. Mismatch возникает, когда первый client render отличается: время, random, browser-only данные, неверный HTML или разные ветки.", caveat: "Не маскируйте проблему suppressHydrationWarning без понимания причины." },
  { match: /Server Components/i, short: "Server Components выполняются на сервере, могут читать server data и не добавляют свой код в client bundle. Client Components дают state, effects, events и browser APIs.", caveat: "Через границу передают сериализуемые props; серверные секреты и модули не должны импортироваться в client graph." },
  { match: /optimistic update/i, short: "UI применяет предполагаемый результат до ответа сервера, хранит контекст для rollback и затем подтверждает либо откатывает изменение.", caveat: "Нужны стабильные temporary IDs, обработка конкурирующих мутаций и понятный UX ошибки." },
  { match: /App Router.*Pages Router/i, short: "App Router строится на React Server Components, nested layouts, streaming и Server Functions. Pages Router использует getServerSideProps/getStaticProps и классическую page-модель.", caveat: "Миграция может быть постепенной, но две системы имеют разные правила data fetching и caching." },
  { match: /use client/i, short: "Директива отмечает границу client module graph. Сам файл и его transitive imports попадают в клиентскую сборку; родитель Server Component всё ещё может передать ему сериализуемые props.", caveat: "Не ставьте use client высоко без необходимости — это расширяет bundle." },
  { match: /Cache Components|use cache/i, short: "В Next.js 16 Cache Components позволяет сочетать статическую оболочку, кэшированные части и runtime-данные. use cache кэширует async-функцию/компонент, а аргументы и closed-over values участвуют в ключе.", caveat: "Request data вроде cookies/headers читают вне cached scope и передают аргументами; персональные данные нельзя случайно разделить между пользователями." },
  { match: /cacheLife|cacheTag|revalidateTag|updateTag/i, short: "cacheLife задаёт срок; cacheTag связывает запись с тегом; revalidateTag помечает её stale для обновления; updateTag нужен для немедленной read-your-own-writes консистентности после мутации.", caveat: "Стратегию выбирают по допустимой устарелости и нагрузке, а не кэшируют всё подряд." },
  { match: /Partial Prerendering/i, short: "PPR заранее создаёт статическую shell страницы, а динамические Suspense-boundaries рендерит и стримит во время запроса.", caveat: "Границы должны соответствовать независимым loading states, иначе waterfall и крупный fallback съедят пользу." },
  { match: /Options API.*Composition API/i, short: "Options API группирует код по типу опции; Composition API — по логической возможности через refs, computed и composables. Composition лучше выводит TypeScript и переиспользует stateful logic.", caveat: "Оба официально поддерживаются; выбирать можно по масштабу и соглашениям команды." },
  { match: /ref.*reactive/i, short: "ref оборачивает любое значение в объект с .value; reactive возвращает Proxy объекта с глубокой реактивностью. В template refs автоматически разворачиваются.", caveat: "Деструктуризация reactive property теряет proxy-доступ; используйте toRefs или computed." },
  { match: /computed.*watch|watchEffect/i, short: "computed — кэшированное чистое производное значение; watch следит за явно заданным source; watchEffect автоматически собирает синхронно прочитанные зависимости для side effect.", caveat: "Не используйте watch для состояния, которое можно выразить computed." },
  { match: /Pinia/i, short: "Pinia даёт соглашения для глобального state: devtools, actions, getters, TypeScript, HMR и SSR-safe создание store.", caveat: "Локальный или небольшой shared state не обязан становиться глобальным store." },
  { match: /dependency injection|injector/i, short: "Angular DI разрешает token через иерархию injectors и создаёт значение по provider recipe. Область provider определяет lifetime и sharing instance.", caveat: "inject() работает только в injection context; вызов в произвольном async callback или lifecycle method вне контекста ошибочен." },
  { match: /ChangeDetectionStrategy\.OnPush|change detection/i, short: "Change detection проверяет bindings и обновляет DOM. OnPush сокращает проверку subtree до notifications: новые input references, events, signals, AsyncPipe или markForCheck.", caveat: "Мутация input-объекта с той же ссылкой может не уведомить OnPush child." },
  { match: /Angular.*signal|signal, computed.*effect/i, short: "Signal хранит значение и уведомляет consumers; computed лениво и memoized выводит значение, динамически отслеживая чтения; effect предназначен для side effects внешних систем.", caveat: "Не переносите derived state через effect — это создаёт циклы и промежуточную несогласованность." },
  { match: /Observable.*Promise/i, short: "Promise даёт один будущий результат и стартует сразу; Observable может выдавать множество значений, лениво стартовать и поддерживает композицию и unsubscribe.", caveat: "Observable не всегда отменяет underlying work автоматически — teardown должен это реализовать." },
  { match: /switchMap.*mergeMap|concatMap.*exhaustMap/i, short: "switchMap отменяет предыдущий inner; mergeMap выполняет параллельно; concatMap ставит в очередь; exhaustMap игнорирует новые до завершения текущего.", example: "Поиск — switchMap; очередь сохранений — concatMap; защита двойного submit — exhaustMap.", caveat: "Выбор определяется семантикой конкуренции и допустимым порядком." },
  { match: /ввода URL/i, short: "Браузер разбирает URL, ищет DNS, устанавливает transport/TLS, отправляет HTTP, парсит HTML, загружает зависимости, строит DOM/CSSOM, layout, paint и composite.", caveat: "Шаги перекрываются: preload scanner и streaming позволяют загружать ресурсы до завершения parsing." },
  { match: /event delegation/i, short: "Один listener на предке обрабатывает события потомков благодаря bubbling и определяет цель через event.target/closest.", caveat: "Не все события bubble одинаково; currentTarget — узел listener, target — исходный узел." },
  { match: /preventDefault.*stopPropagation/i, short: "preventDefault отменяет стандартное действие браузера, если событие cancelable; stopPropagation останавливает дальнейшее распространение.", caveat: "Это независимые операции; passive listener не может вызвать preventDefault." },
  { match: /localStorage.*sessionStorage/i, short: "Оба синхронные string key/value stores одного origin. localStorage переживает закрытие браузера; sessionStorage изолирован вкладкой и живёт до закрытия.", caveat: "Они блокируют main thread и доступны JavaScript, поэтому не подходят для секретов." },
  { match: /IndexedDB/i, short: "IndexedDB — асинхронная транзакционная object database браузера для больших структурированных данных, индексов и offline-сценариев.", caveat: "Схема версионируется через upgrade transaction; ошибки quota и eviction нужно обрабатывать." },
  { match: /Service Worker.*перехватывает/i, short: "Service Worker регистрируется для scope, активируется по lifecycle и получает fetch events, где может ответить из Cache API, сети или своей стратегии.", caveat: "Работает только в secure context, обновляется отдельно от страницы и требует продуманного cache versioning." },
  { match: /same-origin policy/i, short: "Same-origin policy изолирует чтение ресурсов разных scheme/host/port. Некоторые cross-origin отправки разрешены, но чтение ответа требует CORS-разрешения.", caveat: "CORS не защищает сервер от запросов и не заменяет CSRF/authorization." },
  { match: /DNS lookup/i, short: "Resolver проверяет browser/OS caches, обращается к recursive resolver, который получает ответ через root, TLD и authoritative servers; результат кэшируется по TTL.", caveat: "На практике DNS может использовать DoH/DoT, CNAME и CDN routing." },
  { match: /HTTP\/1\.1.*HTTP\/2.*HTTP\/3/i, short: "HTTP/1.1 имеет ограниченный parallelism; HTTP/2 multiplexes streams в одном TCP; HTTP/3 работает поверх QUIC/UDP и избегает TCP head-of-line между streams.", caveat: "Потеря пакета всё ещё влияет на конкретный QUIC stream, а сервер и сеть должны поддерживать протокол." },
  { match: /safe.*idempotent/i, short: "Safe-метод не должен изменять состояние (GET/HEAD). Idempotent означает, что повтор того же запроса имеет тот же intended effect (PUT/DELETE тоже idempotent).", caveat: "Сервер может логировать safe request; idempotent не означает отсутствие побочных действий вообще." },
  { match: /CORS/i, short: "CORS — браузерный протокол, позволяющий серверу через response headers разрешить JavaScript читать cross-origin ответ. Несimple запросы предваряются OPTIONS preflight.", caveat: "Не отражайте произвольный Origin с credentials; CORS не является authentication или firewall." },
  { match: /Cache-Control.*ETag|no-cache.*no-store|stale-while-revalidate/i, short: "Cache-Control задаёт хранение и свежесть; no-store запрещает хранение, no-cache требует revalidation. ETag позволяет условный запрос и 304, stale-while-revalidate временно отдаёт stale и обновляет фоновой проверкой.", caveat: "Персонализированный ответ требует правильных private/Vary/cache key настроек." },
  { match: /cookie.*SameSite|HttpOnly|Secure/i, short: "HttpOnly скрывает cookie от JS; Secure ограничивает HTTPS; SameSite управляет cross-site отправкой; Domain/Path задают область доставки.", caveat: "Это defense in depth: cookie всё равно автоматически уходит серверу и требует CSRF-модели." },
  { match: /Broken Access Control|IDOR|BOLA/i, short: "Broken Access Control возникает, когда сервер не проверяет право субъекта на каждое действие/объект. IDOR/BOLA — доступ к чужому ресурсу через изменяемый идентификатор.", caveat: "Скрытая кнопка и непредсказуемый ID не защита; проверка должна быть server-side deny-by-default." },
  { match: /XSS/i, short: "XSS выполняет атакующий код в origin приложения через небезопасный вывод или DOM sink. Защита: contextual escaping, безопасные APIs, sanitization для разрешённого HTML, CSP и Trusted Types.", caveat: "HttpOnly снижает кражу cookie, но XSS всё ещё может действовать от имени пользователя." },
  { match: /CSRF/i, short: "CSRF заставляет браузер аутентифицированного пользователя отправить нежелательный state-changing запрос. Защита: SameSite, CSRF token, проверка Origin и отсутствие мутаций через GET.", caveat: "XSS обычно обходит CSRF token, поэтому нужны обе защиты." },
  { match: /CSP|Trusted Types/i, short: "CSP ограничивает источники scripts/styles и другие возможности; nonce/hash позволяет доверенные scripts. Trusted Types запрещает опасным DOM sinks принимать обычные строки.", caveat: "CSP — дополнительный слой, а не замена escaping и исправления unsafe sinks." },
  { match: /JWT/i, short: "JWT — подписанный набор claims, а не зашифрованная сессия. Сервер обязан проверить алгоритм, подпись, issuer, audience и время; authorization проверяется отдельно.", caveat: "Долгоживущий JWT трудно отозвать; для многих веб-приложений opaque session cookie проще и безопаснее." },
  { match: /OAuth.*PKCE/i, short: "Authorization Code + PKCE отправляет пользователя к authorization server, а клиент меняет одноразовый code вместе с verifier. Challenge связывает code с инициировавшим клиентом.", caveat: "OAuth делегирует доступ; для identity нужен OIDC. Redirect URI и state/nonce должны строго проверяться." },
  { match: /WebAuthn|passkeys/i, short: "WebAuthn использует origin-bound public-key credentials: сервер хранит public key, authenticator подписывает challenge. Passkey может синхронизироваться между устройствами.", caveat: "Нужны recovery и управление несколькими credentials; phishing resistance зависит от корректной origin/RP ID настройки." },
  { match: /переменные окружения.*секрет|frontend bundle/i, short: "Всё, что нужно клиентскому JavaScript, пользователь может прочитать из bundle, DevTools или network. Frontend env-переменные — build-time configuration, не секреты.", caveat: "Секретные ключи хранят на сервере; клиент получает только ограниченный результат через авторизованный API." },
  { match: /unit, integration.*E2E|test pyramid|testing trophy/i, short: "Unit изолирует малую логику; integration проверяет совместную работу частей; E2E — критический поток через реальную систему. Больше быстрых integration/unit и немного ценных E2E дают устойчивую обратную связь.", caveat: "Граница зависит от системы; важнее уверенность и стоимость поддержки, а не форма пирамиды." },
  { match: /mock/i, short: "Mock заменяет collaborator и проверяет взаимодействие; stub возвращает данные; spy наблюдает вызовы; fake имеет упрощённую рабочую реализацию.", caveat: "Не мокайте собственные детали реализации и всё подряд: тест начнёт подтверждать mock setup, а не поведение продукта." },
  { match: /flaky/i, short: "Flaky-тест зависит от времени, порядка, сети, shared state, animation или нестабильного selector. Исправляют детерминированными ожиданиями, изоляцией и контролем окружения.", caveat: "Автоматический retry маскирует симптом и допустим только вместе с расследованием причины." },
  { match: /LCP, INP.*CLS|Core Web Vitals/i, short: "LCP измеряет время появления крупнейшего контентного элемента; INP — задержку взаимодействий по всей сессии; CLS — неожиданные layout shifts.", caveat: "Оценивайте field data по 75-му percentile отдельно для mobile/desktop; lab помогает диагностировать, но не заменяет RUM." },
  { match: /Long Task/i, short: "Main-thread task длиннее 50 мс считается Long Task и блокирует input/render. Её разбивают на меньшие задачи, уменьшают JS или выносят CPU работу в worker.", caveat: "Просто завернуть всё в setTimeout может ухудшить total latency; нужен приоритет и измерение." },
  { match: /preload, preconnect.*prefetch/i, short: "preconnect заранее создаёт connection; preload повышает приоритет ресурса текущей навигации; prefetch загружает вероятный ресурс будущей навигации с низким приоритетом.", caveat: "Лишние hints конкурируют за bandwidth и могут замедлить критические ресурсы." },
  { match: /performance budget/i, short: "Performance budget задаёт измеримые лимиты: JS/CSS bytes, image weight, timings и Web Vitals. CI и RUM отслеживают регрессии.", caveat: "Budget должен быть привязан к устройствам, сети и продуктовой цели, иначе это формальная цифра." },
  { match: /микрофронтенд/i, short: "Микрофронтенды дают организационно независимые вертикальные части с отдельными релизами. Интеграция возможна build-time packages, runtime modules, iframes или server composition.", caveat: "Цена — дублирование, сложные routing/auth/observability и UX-consistency; без автономных команд обычно это лишняя сложность." },
  { match: /ADR/i, short: "ADR фиксирует контекст, принятое решение, альтернативы и последствия. Он объясняет почему, а не дублирует код.", caveat: "ADR должен быть коротким, версионируемым и обновляться статусом, а не переписываться задним числом." },
  { match: /feature flags|rollout/i, short: "Flag отделяет deploy от release, позволяет percentage/cohort rollout и быстрый kill switch. Сервер остаётся источником authorization.", caveat: "У каждого флага нужен owner и дата удаления, иначе растёт число комбинаций и мёртвого кода." },
  { match: /observability/i, short: "Frontend observability объединяет errors, logs, performance metrics, user actions и distributed traces с release/session correlation.", caveat: "Собирайте минимум нужных данных, редактируйте PII и используйте sampling." },
  { match: /начинаете frontend system design/i, short: "Сначала уточняют пользователей, основные сценарии, масштаб и SLO; затем данные/API, state, rendering, performance, reliability, security и observability; в конце обсуждают trade-offs.", caveat: "Не начинайте с выбора фреймворка до требований и bottlenecks." },
  { match: /Cursor pagination.*offset/i, short: "Offset прост и позволяет переход к странице, но дорог на больших смещениях и нестабилен при вставках. Cursor опирается на стабильный порядок и лучше для меняющихся лент.", caveat: "Cursor должен включать уникальный tie-breaker и быть opaque для клиента." },
  { match: /OT.*CRDT/i, short: "OT преобразует конкурентные операции относительно друг друга и обычно требует координации; CRDT проектирует операции/состояния так, чтобы они коммутировали и сходились.", caveat: "CRDT упрощает offline merge, но увеличивает metadata и сложность модели; универсально лучшего подхода нет." },
  { match: /chunked.*resumable upload/i, short: "Файл делят на chunks, сервер создаёт upload session, каждый chunk получает номер/checksum, а финализация атомарно собирает объект. Клиент повторяет только отсутствующие части.", caveat: "Нужны лимиты, expiry незавершённых сессий, idempotency и проверка файла после сборки." },
  { match: /идемпотент/i, short: "Идемпотентная операция при повторе с тем же ключом не создаёт новый эффект. Клиент передаёт idempotency key, сервер хранит результат/статус первой обработки.", caveat: "Ключ должен быть scoped к пользователю и операции и иметь срок хранения." },
  { match: /временную.*пространственную сложность|O\(n/i, short: "Временная сложность оценивает рост числа операций, пространственная — дополнительной памяти, относительно размера входа. Учитывают worst/average case и реальные ограничения.", caveat: "Big O скрывает константы, cache locality и сетевые/DOM-стоимости; после выбора класса всё равно измеряйте." },
  { match: /два числа.*сумм/i, short: "Проходите массив один раз, храните увиденные числа в Map/Set и для x проверяйте target-x. Время O(n), память O(n).", caveat: "Уточните, нужны значения или индексы, допустимы ли повторы и существует ли ровно одно решение." },
  { match: /скобочн/i, short: "Используйте stack: открывающую скобку кладите, для закрывающей проверяйте вершину и снимайте. В конце stack должен быть пуст. O(n) времени, O(n) памяти.", caveat: "Закрывающая при пустом stack немедленно делает строку невалидной." },
  { match: /binary search/i, short: "На отсортированном диапазоне сравнивайте middle и отбрасывайте половину. Обычно удобно хранить полуинтервал [left,right), чтобы уменьшить off-by-one. O(log n).", caveat: "Сначала сформулируйте invariant и отдельно проверьте пустой массив и границы." },
  { match: /Promise\.all.*реализовать/i, short: "Создайте Promise, сохраните результаты по исходным индексам, оберните каждый элемент Promise.resolve, считайте fulfilled и reject сразу по первой ошибке.", caveat: "Пустой iterable должен fulfilled с []; порядок результата равен входу, не порядку завершения." },
  { match: /LRU cache/i, short: "Map хранит key→node, двусвязный список — порядок использования. get/mutate переносит node в head; при превышении capacity удаляется tail. Операции O(1).", caveat: "Уточните поведение capacity=0, обновление существующего ключа и memory accounting." },
  { match: /сложн.*техническ.*решени|trade-offs/i, short: "Сильный ответ строят по STAR: контекст и цель, ваша ответственность, варианты и критерии, решение, измеримый результат и то, что изменили бы сейчас.", caveat: "Не перечисляйте технологии без причин; покажите ограничения, данные и собственный вклад." },
  { match: /production.*ошибк|production-инцидент|root cause/i, short: "Сначала ограничьте ущерб и восстановите сервис, затем сохраните данные, найдите root cause, добавьте corrective actions и проведите blameless review.", caveat: "Root cause редко равен одной человеческой ошибке; ищите системные условия и пробелы обнаружения." },
];

const categoryDefaults: Record<string, InterviewAnswer> = {
  "HTML и доступность": {
    short: "Ответ должен опираться на нативную семантику, предсказуемое клавиатурное поведение и корректное представление в accessibility tree.",
    points: ["Сначала назовите подходящий HTML-элемент и встроенное поведение.", "Затем объясните фокус, accessible name, состояния и fallback без JavaScript."],
    example: "Проверьте сценарий мышью, клавиатурой и скринридером, а не только визуально.",
    caveat: "ARIA дополняет HTML, но не исправляет неверную структуру и не добавляет поведение.",
  },
  CSS: {
    short: "Объясняйте CSS через layout-модель: formatting context, intrinsic size, containing block, cascade и этапы rendering.",
    points: ["Назовите условие, при котором правило применяется.", "Покажите минимальный пример и объясните влияние на layout/paint/composite."],
    example: "Проверьте поведение на узком контейнере, длинном контенте и разных writing modes.",
    caveat: "Не лечите layout случайными z-index, overflow и fixed dimensions без понимания причины.",
  },
  "JavaScript: язык": {
    short: "Разберите точный алгоритм языка: типы операндов, scope, binding, преобразование или поиск свойства.",
    points: ["Сначала дайте определение, затем пошагово опишите выполнение.", "Добавьте короткий пример кода и граничный случай."],
    example: "Покажите ожидаемый результат выражения и объясните его без фразы «так работает JavaScript».",
    caveat: "Отделяйте спецификацию языка от оптимизаций конкретного движка.",
  },
  "JavaScript: глубоко": {
    short: "Ответ строится от спецификационной модели к реализации движка и практическим последствиям для памяти и производительности.",
    points: ["Уточните, что гарантирует стандарт.", "Оптимизации движка описывайте как возможную реализацию, а не контракт."],
    example: "Свяжите механизм с профилированием, утечкой памяти или размером bundle.",
    caveat: "Микрооптимизации без измерений обычно менее важны, чем алгоритм и архитектура данных.",
  },
  "Асинхронность и Event Loop": {
    short: "Нарисуйте порядок: текущий call stack → завершение task → очистка microtasks → возможный render → следующая task.",
    points: ["Укажите момент постановки callback в очередь.", "Разделите параллельный I/O и однопоточное выполнение JavaScript."],
    example: "Предскажите порядок console.log для Promise, queueMicrotask и setTimeout.",
    caveat: "Promise не отменяет underlying operation и сам по себе не делает CPU-работу параллельной.",
  },
  TypeScript: {
    short: "Покажите, какую связь между значениями выражает тип и какую ошибку он предотвращает на этапе компиляции.",
    points: ["Отделите compile-time модель от runtime validation.", "Предпочитайте inference и narrowing необоснованным assertions."],
    example: "Приведите минимальный generic или discriminated union и покажите ошибку compiler.",
    caveat: "Сложный тип не должен быть труднее доменной модели, которую он защищает.",
  },
  "React: основа": {
    short: "Объясните вопрос через snapshot state, чистый render, identity позиции в дереве и отдельную commit-фазу.",
    points: ["Назовите, что вызывает render.", "Объясните, сохраняется или сбрасывается state и почему."],
    example: "Покажите обновление state без мутации и со стабильным key.",
    caveat: "Render не равен изменению DOM: React может вычислить дерево и ничего не commit.",
  },
  "React: хуки и эффекты": {
    short: "Хук вызывается в стабильном порядке на каждом render; effect используют только для синхронизации с внешней системой.",
    points: ["Определите reactive dependencies.", "Опишите setup, cleanup и поведение при повторном запуске."],
    example: "Подписка создаётся в effect и полностью удаляется cleanup-функцией.",
    caveat: "Не храните derived state и не обрабатывайте user event через effect.",
  },
  "React: advanced": {
    short: "Объясните разделение render/commit, приоритеты обновлений, границы server/client и UX loading/error states.",
    points: ["Покажите, какую работу можно прервать или стримить.", "Обсудите bundle, hydration, cache и consistency."],
    example: "Разместите Suspense вокруг независимой части страницы, а Error Boundary — вокруг изолируемой зоны отказа.",
    caveat: "Concurrent rendering меняет моменты выполнения, но не разрешает нечистый render.",
  },
  "Next.js": {
    short: "Сначала определите место выполнения — build, server request или browser — затем правила caching, serialization и invalidation.",
    points: ["Server Component используйте по умолчанию.", "Client boundary делайте минимальной и проверяйте authorization на сервере."],
    example: "Статическая оболочка может содержать Suspense-boundary с runtime-данными.",
    caveat: "Кэширование персонального ответа без корректного ключа приводит к утечке данных.",
  },
  Vue: {
    short: "Объясните proxy/ref reactivity: чтение регистрирует dependency, запись уведомляет effects и планирует update.",
    points: ["Разделите чистый computed и side-effect watch.", "Покажите границу component state, composable и global store."],
    example: "Для большого immutable массива используйте shallowRef и заменяйте root value.",
    caveat: "Деструктуризация reactive property может потерять реактивность.",
  },
  Angular: {
    short: "Свяжите ответ с DI scope, change-detection notification, signals/RxJS и lifecycle rendering.",
    points: ["Назовите owner состояния и lifetime зависимости.", "Объясните, что уведомляет view об изменении."],
    example: "Signal читается в OnPush template и автоматически отмечает component для проверки.",
    caveat: "Side effect не должен заменять computed state, а subscription обязан иметь teardown.",
  },
  "Браузер и Web API": {
    short: "Опишите API в контексте origin, lifecycle страницы, main thread и rendering pipeline.",
    points: ["Назовите момент выполнения callback.", "Укажите ограничения безопасности и cleanup."],
    example: "Измерение layout группируют отдельно от DOM writes, чтобы не вызвать layout thrashing.",
    caveat: "Поддержка API, permissions и page lifecycle различаются — нужен fallback.",
  },
  "Сеть и HTTP": {
    short: "Разберите запрос по слоям: DNS/transport/TLS → HTTP semantics → cache → browser security → application state.",
    points: ["Укажите, кто обеспечивает свойство: браузер, proxy или сервер.", "Обсудите retry, idempotency и observability."],
    example: "GET кэшируется с ETag, а повтор POST защищается idempotency key.",
    caveat: "Успешный HTTP status не гарантирует корректность доменного результата.",
  },
  Безопасность: {
    short: "Сформулируйте актив, границу доверия, способ атаки и server-side контроль, который предотвращает или ограничивает ущерб.",
    points: ["Используйте deny-by-default и проверяйте authorization для каждого объекта.", "Добавляйте defense in depth: безопасные defaults, headers, logging и monitoring."],
    example: "Даже если UI скрывает действие, API повторно проверяет пользователя, ресурс и разрешённую операцию.",
    caveat: "Валидация на клиенте улучшает UX, но не является security boundary.",
  },
  Тестирование: {
    short: "Тестируйте наблюдаемое поведение через публичный интерфейс на самом низком уровне, который даёт достаточную уверенность.",
    points: ["Сделайте setup детерминированным.", "Проверяйте результат, а не последовательность внутренних вызовов без необходимости."],
    example: "Пользователь вводит данные, отправляет форму и видит результат; сеть заменена реалистичным protocol-level fake.",
    caveat: "100% coverage не означает полезных assertions и не ловит отсутствующие требования.",
  },
  Performance: {
    short: "Сначала измерьте field/lab метрику и найдите bottleneck, затем измените одну причину и повторите измерение.",
    points: ["Разделите network, main thread, rendering и memory.", "Оптимизируйте критический пользовательский путь, а не абстрактный benchmark."],
    example: "Для высокого INP найдите Long Task обработчика и разбейте вычисление или вынесите его в worker.",
    caveat: "Оптимизация одной метрики может ухудшить другую; используйте budgets и реальные устройства.",
  },
  "Архитектура frontend": {
    short: "Границы проводят по бизнес-возможностям, ownership и направлению зависимостей; решение оценивают по изменяемости и стоимости координации.",
    points: ["Сформулируйте требования и альтернативы.", "Назовите migration path, failure modes и observability."],
    example: "Feature экспортирует небольшой public API, а внутренние компоненты не импортируются соседями напрямую.",
    caveat: "Архитектура должна соответствовать масштабу команды; преждевременное распределение увеличивает стоимость.",
  },
  "Frontend System Design": {
    short: "Уточните требования и масштаб, затем последовательно спроектируйте данные, API, state, rendering, performance, reliability, security и наблюдаемость.",
    points: ["Зафиксируйте SLO и критические пользовательские потоки.", "Для каждого решения назовите альтернативу и trade-off."],
    example: "Лента использует cursor pagination, normalized cache, virtualization и восстановление scroll position.",
    caveat: "Не пытайтесь спроектировать всё: углубляйтесь в bottlenecks конкретного продукта.",
  },
  "Алгоритмы и задачи": {
    short: "Сначала уточните контракт и edge cases, предложите простое решение, затем оптимизируйте и докажите сложность.",
    points: ["Назовите invariant структуры данных.", "Пройдите пример вручную и оцените time/space complexity."],
    example: "Map часто заменяет вложенный поиск: O(n²) превращается в ожидаемое O(n) ценой O(n) памяти.",
    caveat: "Не кодируйте до согласования входа, результата, дубликатов и ограничений.",
  },
  "Инженерные и поведенческие": {
    short: "Используйте STAR: конкретный контекст, ваша задача, действия и измеримый результат; затем честно назовите урок.",
    points: ["Отделите собственный вклад от командного.", "Покажите критерии решения и работу с неопределённостью."],
    example: "«Снизили p75 INP с 380 до 180 мс» сильнее, чем «улучшили производительность».",
    caveat: "Не обвиняйте людей и не скрывайте неудачу; покажите системное мышление.",
  },
};

export function getAnswer(item: InterviewQuestion): InterviewAnswer {
  const rule = rules.find((candidate) => candidate.match.test(item.question));
  const fallback = categoryDefaults[item.category] ?? categoryDefaults["Инженерные и поведенческие"];

  if (!rule) return fallback;

  return {
    short: rule.short,
    points: rule.points?.length ? rule.points : fallback.points,
    example: rule.example ?? fallback.example,
    caveat: rule.caveat ?? fallback.caveat,
  };
}
