export type InterviewQuestion = {
  id: string;
  category: string;
  level: "Junior" | "Middle" | "Senior";
  question: string;
};

type QuestionGroup = {
  category: string;
  level: InterviewQuestion["level"];
  questions: string[];
};

const groups: QuestionGroup[] = [
  {
    category: "HTML и доступность",
    level: "Junior",
    questions: [
      "Что такое семантическая HTML-разметка и зачем она нужна?",
      "Чем block, inline и inline-block элементы отличаются друг от друга?",
      "Когда использовать button, а когда ссылку a?",
      "Чем section отличается от article, main, aside и div?",
      "Что такое поток документа и как элемент может из него выпасть?",
      "Для чего нужен doctype и что такое quirks mode?",
      "Как связать label с input и почему placeholder не заменяет label?",
      "Какие типы input вы знаете и что даёт правильный type?",
      "Что такое data-атрибуты и когда их стоит использовать?",
      "В чём разница между defer, async и обычным script?",
      "Что такое progressive enhancement?",
      "Как picture, srcset и sizes помогают загружать адаптивные изображения?",
      "Что такое нативная валидация формы и Constraint Validation API?",
      "Какие meta-теги обязательны для современной страницы?",
      "Что попадает в accessibility tree?",
      "Как проверить страницу только с клавиатуры?",
      "Для чего нужны tabindex=0 и tabindex=-1 и почему опасен tabindex>0?",
      "Что такое accessible name и откуда он берётся?",
      "Когда допустимо применять ARIA?",
      "Чем aria-label отличается от aria-labelledby и aria-describedby?",
    ],
  },
  {
    category: "CSS",
    level: "Junior",
    questions: [
      "Как браузер вычисляет специфичность CSS-селектора?",
      "Что такое каскад, наследование и initial value?",
      "Как работает box model и что меняет box-sizing: border-box?",
      "В чём разница между margin и padding?",
      "Почему схлопываются вертикальные margin и когда этого не происходит?",
      "Что создаёт новый stacking context?",
      "Почему z-index иногда не работает?",
      "Чем position relative, absolute, fixed и sticky отличаются друг от друга?",
      "Как работает containing block для absolutely positioned элемента?",
      "Когда выбрать Flexbox, а когда CSS Grid?",
      "В чём разница между justify-content, align-items и align-content?",
      "Почему flex-элемент может не сжиматься и как помогает min-width: 0?",
      "Как работают grid-template-areas, minmax и auto-fit/auto-fill?",
      "Что такое BFC и какие проблемы он решает?",
      "Чем display: none отличается от visibility: hidden и opacity: 0?",
      "В чём разница между pseudo-class и pseudo-element?",
      "Как сделать адаптивную типографику с clamp?",
      "Media query или container query: как выбрать?",
      "Что такое CSS logical properties и зачем они нужны?",
      "Какие CSS-свойства дешевле всего анимировать?",
      "Что вызывают layout, paint и composite?",
      "Что делает will-change и почему им нельзя злоупотреблять?",
      "Что такое CSS Modules, CSS-in-JS и utility-first подход?",
      "Как @layer управляет порядком каскада?",
      "Как реализовать светлую и тёмную темы без лишних перерисовок?",
    ],
  },
  {
    category: "JavaScript: язык",
    level: "Junior",
    questions: [
      "Какие типы данных есть в JavaScript?",
      "Почему typeof null возвращает object?",
      "Чем примитив отличается от объекта?",
      "В чём разница между == и ===?",
      "Какие значения являются falsy?",
      "Чем null отличается от undefined?",
      "Что такое неявное преобразование типов?",
      "Почему NaN не равен самому себе и как его корректно проверить?",
      "Чем var отличается от let и const?",
      "Что такое hoisting и temporal dead zone?",
      "Что такое область видимости и лексическое окружение?",
      "Что такое замыкание и где оно применяется?",
      "Как определяется значение this?",
      "Чем стрелочная функция отличается от обычной?",
      "Как работают call, apply и bind?",
      "Что происходит при вызове функции с new?",
      "Как устроена цепочка прототипов?",
      "Чем class отличается от функции-конструктора?",
      "Какие способы копирования объекта вы знаете?",
      "Почему spread не делает глубокую копию?",
      "Чем Object.freeze отличается от const?",
      "Как работают getters и setters?",
      "Чем Map отличается от обычного объекта?",
      "Когда использовать Set, WeakMap и WeakSet?",
      "Как работает деструктуризация и rest/spread?",
      "Что такое optional chaining и nullish coalescing?",
      "Чем for...in отличается от for...of?",
      "Какие методы массива мутируют исходный массив?",
      "Чем map, filter, reduce и flatMap отличаются по назначению?",
      "Как корректно сортировать числа через Array.prototype.sort?",
    ],
  },
  {
    category: "JavaScript: глубоко",
    level: "Middle",
    questions: [
      "Что такое execution context и из каких частей он состоит?",
      "Как движок разрешает идентификатор по scope chain?",
      "Как closure влияет на время жизни объектов в памяти?",
      "Что такое property descriptor и чем data descriptor отличается от accessor descriptor?",
      "Как Object.create влияет на prototype chain?",
      "Что такое hidden classes/shapes и как они связаны с производительностью?",
      "Как работает garbage collector на основе достижимости?",
      "Какие типичные утечки памяти возникают во frontend-приложении?",
      "Почему удалённый DOM-узел может остаться в памяти?",
      "Когда WeakMap помогает избежать утечки?",
      "Что такое iterator protocol и iterable protocol?",
      "Как работают generator-функции?",
      "Что такое Proxy и Reflect и какие у Proxy ограничения?",
      "Как устроены ES Modules и live bindings?",
      "Чем CommonJS отличается от ESM?",
      "Что такое tree shaking и какие условия ему нужны?",
      "Как работает structuredClone и что он не умеет клонировать?",
      "Что такое tagged template literal?",
      "Как обрабатываются ошибки в sync и async коде?",
      "Почему нельзя бездумно ловить все ошибки пустым catch?",
      "Как спроектировать immutable update вложенной структуры?",
      "Что такое currying и partial application?",
      "Чем debounce отличается от throttle?",
      "Как реализовать once, memoize и compose?",
      "Как обеспечить стабильность сортировки и зачем она нужна?",
    ],
  },
  {
    category: "Асинхронность и Event Loop",
    level: "Middle",
    questions: [
      "Что такое call stack, task queue и microtask queue?",
      "В каком порядке выполняются Promise.then, queueMicrotask и setTimeout?",
      "Когда браузер получает возможность отрисовать кадр?",
      "Может ли длинная цепочка микрозадач заблокировать UI?",
      "Как Promise меняет своё состояние?",
      "Чем Promise.all отличается от allSettled, race и any?",
      "Почему Promise внутри forEach часто работает не так, как ожидают?",
      "Как выполнить асинхронные операции последовательно и параллельно?",
      "Как ограничить число одновременно выполняющихся запросов?",
      "Как работает async/await под капотом?",
      "Что вернёт async-функция при throw?",
      "Как правильно обрабатывать ошибки нескольких параллельных запросов?",
      "Что такое AbortController и как отменять fetch?",
      "Как избежать race condition при быстром поиске?",
      "Как реализовать retry с exponential backoff и jitter?",
      "Какие операции блокируют main thread?",
      "Когда использовать Web Worker?",
      "Чем Web Worker отличается от Service Worker?",
      "Как передаются данные между worker и главным потоком?",
      "Что такое Long Task и как найти её в профилировщике?",
    ],
  },
  {
    category: "TypeScript",
    level: "Middle",
    questions: [
      "Что такое структурная типизация?",
      "Чем interface отличается от type alias?",
      "Чем any отличается от unknown и never?",
      "Когда TypeScript выводит тип never?",
      "Что такое union и intersection types?",
      "Как работает control-flow narrowing?",
      "Что такое discriminated union?",
      "Как написать пользовательский type guard?",
      "Что означает оператор satisfies?",
      "Чем as const отличается от обычного type assertion?",
      "Почему type assertion не выполняет runtime-проверку?",
      "Как типизировать словарь с Record?",
      "Что такое generic и когда он лучше union?",
      "Как ограничить generic через extends?",
      "Что делает keyof и indexed access type?",
      "Как работают mapped types?",
      "Как работают conditional types?",
      "Почему conditional type может распределяться по union?",
      "Что делает infer в conditional type?",
      "Как реализованы Partial, Required, Pick, Omit и ReturnType?",
      "Что такое variance, covariance и contravariance?",
      "Как strictFunctionTypes влияет на функции?",
      "Чем overload отличается от функции с union-параметром?",
      "Как типизировать React-компонент с polymorphic as prop?",
      "Как типизировать API-ответ, если данным нельзя доверять?",
      "Для чего нужны declaration files и module augmentation?",
      "Как project references помогают большому monorepo?",
      "Какие strict-флаги TypeScript вы считаете обязательными?",
      "Что такое branded/opaque types и где они полезны?",
      "Как не допустить расхождения runtime-схемы и TypeScript-типа?",
    ],
  },
  {
    category: "React: основа",
    level: "Junior",
    questions: [
      "Что делает React декларативным?",
      "Что такое компонент и какие требования предъявляются к нему?",
      "Чем props отличаются от state?",
      "Что запускает повторный рендер компонента?",
      "Что происходит на render и commit фазах?",
      "Что такое reconciliation?",
      "Зачем React нужны стабильные keys?",
      "Почему индекс массива — плохой key для изменяемого списка?",
      "Почему нельзя мутировать state напрямую?",
      "Как React объединяет или заменяет обновления состояния?",
      "Что такое batching?",
      "Зачем передавать функцию в setState?",
      "Что такое controlled и uncontrolled components?",
      "Как поднять состояние вверх?",
      "Что такое composition и children?",
      "Как работает Context и какие у него ограничения?",
      "Когда useReducer лучше useState?",
      "Что хранит useRef и почему его изменение не запускает render?",
      "Чем ref отличается от state?",
      "Что такое portal и где он нужен?",
      "Для чего нужен Fragment?",
      "Как обрабатываются события в React?",
      "Что такое SyntheticEvent?",
      "Как корректно отрисовать условный UI?",
      "Почему компонент должен быть чистым на этапе render?",
    ],
  },
  {
    category: "React: хуки и эффекты",
    level: "Middle",
    questions: [
      "Какие правила хуков существуют и почему?",
      "Когда useEffect вообще не нужен?",
      "Как правильно определить зависимости effect?",
      "Что такое stale closure?",
      "Как очистить таймер, подписку и сетевой запрос в effect?",
      "Почему effect в Strict Mode может выполниться дважды в development?",
      "Чем useEffect отличается от useLayoutEffect?",
      "Почему derived state обычно не нужно хранить в state?",
      "Как синхронизировать компонент с внешней системой?",
      "Как избежать бесконечного цикла useEffect?",
      "Когда useMemo действительно даёт пользу?",
      "Почему useMemo не является семантической гарантией?",
      "Когда useCallback помогает, а когда добавляет шум?",
      "Чем React.memo отличается от useMemo?",
      "Как работает пользовательский hook?",
      "Какие части состояния стоит извлекать в custom hook?",
      "Как использовать useSyncExternalStore?",
      "Как избежать tearing при чтении внешнего store?",
      "Как обрабатывать async-логику без async callback у useEffect?",
      "Как спроектировать hook с хорошим и стабильным API?",
      "Что такое Effect Event и какую проблему он решает?",
      "Как React Compiler меняет подход к ручной мемоизации?",
    ],
  },
  {
    category: "React: advanced",
    level: "Senior",
    questions: [
      "Как Fiber позволяет прерывать и приоритизировать работу?",
      "Что означает concurrent rendering?",
      "Чем transition update отличается от urgent update?",
      "Как работают useTransition и useDeferredValue?",
      "Что делает Suspense и чего он сам по себе не делает?",
      "Как Error Boundary взаимодействует с Suspense?",
      "Что такое hydration и почему возникают hydration mismatch?",
      "Чем SSR, SSG, CSR и streaming SSR отличаются по trade-offs?",
      "Что такое React Server Components?",
      "Какие данные можно передавать через границу Server/Client Components?",
      "Как Server Actions влияют на модель мутаций?",
      "Как оптимизировать Context, который часто обновляется?",
      "Когда внешний state manager оправдан?",
      "Server state, client state, form state и URL state: где границы?",
      "Как нормализовать состояние сложного интерфейса?",
      "Что такое optimistic update и как выполнить rollback?",
      "Как виртуализировать большой список переменной высоты?",
      "Как профилировать лишние рендеры?",
      "Как спроектировать compound components?",
      "Controlled props, state reducer и render props: когда применять?",
      "Как обеспечить accessibility headless-компонента?",
      "Как избежать waterfall запросов в React-приложении?",
      "Какие ошибки вызывает неправильное размещение Suspense boundaries?",
      "Как построить frontend observability для React-приложения?",
      "Как безопасно выполнить постепенную миграцию большого React-кода?",
    ],
  },
  {
    category: "Next.js",
    level: "Senior",
    questions: [
      "Чем App Router отличается от Pages Router?",
      "Почему pages и layouts в App Router по умолчанию Server Components?",
      "Когда компонент должен стать Client Component?",
      "Что именно означает директива use client?",
      "Как уменьшить клиентский bundle при работе с Client Components?",
      "Как работает streaming с Suspense?",
      "Чем loading.tsx отличается от ручного Suspense boundary?",
      "Как работают nested layouts и route groups?",
      "Что такое parallel routes и intercepting routes?",
      "Route Handler или Server Action: как выбрать?",
      "Как валидировать и авторизовывать Server Action?",
      "Какие риски безопасности возникают у Server Actions?",
      "Как устроены prefetch и client-side navigation?",
      "Чем static rendering отличается от dynamic rendering?",
      "Что такое Cache Components в Next.js 16?",
      "Как директива use cache определяет ключ кэша?",
      "Чем cacheLife, cacheTag, revalidateTag и updateTag отличаются?",
      "Когда данные нужно оставить uncached и обернуть в Suspense?",
      "Как cookies и headers влияют на рендеринг и кэширование?",
      "Как избежать утечки персональных данных через общий кэш?",
      "Что такое Partial Prerendering?",
      "Как работает ISR и где хранится его кэш?",
      "Как синхронизировать invalidation в multi-instance deployment?",
      "Как оптимизируются изображения и шрифты?",
      "Какие причины hydration mismatch типичны для Next.js?",
      "Как организовать authentication и authorization в App Router?",
      "Middleware или серверная проверка в route: где должна быть защита?",
      "Как мониторить cold starts, server timing и Web Vitals?",
      "Какие trade-offs у self-hosting Next.js?",
      "Как тестировать Server Components и Server Actions?",
    ],
  },
  {
    category: "Vue",
    level: "Middle",
    questions: [
      "Чем Options API отличается от Composition API?",
      "Почему Composition API удобнее для повторного использования логики?",
      "Как Vue отслеживает зависимости реактивного состояния?",
      "Чем ref отличается от reactive?",
      "Почему деструктуризация reactive-объекта может потерять реактивность?",
      "Как работают computed и watch?",
      "Чем watchEffect отличается от watch?",
      "Что такое composable и как спроектировать его API?",
      "Как устроен lifecycle Vue-компонента?",
      "Как работают props и emits?",
      "Что такое slots и scoped slots?",
      "Как работает v-model у пользовательского компонента?",
      "Что делают provide и inject?",
      "Когда нужен Pinia?",
      "Почему глобальный reactive singleton опасен при SSR?",
      "Как работают async components и Suspense?",
      "Что вызывает update компонента Vue?",
      "Когда использовать shallowRef и shallowReactive?",
      "Как оптимизировать очень большой список?",
      "Что делают v-once и v-memo?",
      "Какие причины hydration mismatch встречаются во Vue?",
      "Как типизировать props, emits и slots в script setup?",
    ],
  },
  {
    category: "Angular",
    level: "Middle",
    questions: [
      "Что такое component, directive, pipe и service в Angular?",
      "Как работает dependency injection и иерархия injector?",
      "Что такое injection context?",
      "Чем template-driven формы отличаются от reactive forms?",
      "Как работает change detection?",
      "Что меняет ChangeDetectionStrategy.OnPush?",
      "Что такое Zone.js и зачем Angular исторически его использовал?",
      "Как работает zoneless Angular?",
      "Что такое signal, computed и effect?",
      "Как Angular динамически отслеживает зависимости signal?",
      "Почему computed ленивый и memoized?",
      "Когда effect является неправильным выбором?",
      "Чем Observable отличается от Promise?",
      "Что такое cold и hot Observable?",
      "Чем Subject, BehaviorSubject и ReplaySubject отличаются?",
      "Как избежать утечек RxJS-подписок?",
      "Когда switchMap лучше mergeMap, concatMap и exhaustMap?",
      "Что такое standalone components?",
      "Как работают lazy routes и code splitting?",
      "Что такое Angular SSR и hydration?",
      "Почему некорректный HTML может сломать hydration?",
      "Как TransferState предотвращает повторную загрузку данных?",
      "Как защититься от XSS средствами Angular?",
      "Как тестировать component, service и signal-based state?",
    ],
  },
  {
    category: "Браузер и Web API",
    level: "Middle",
    questions: [
      "Что происходит от ввода URL до появления пикселей на экране?",
      "Как строятся DOM, CSSOM и render tree?",
      "Что блокирует парсинг HTML и первый рендер?",
      "Что такое layout, paint и compositing?",
      "Что вызывает forced synchronous layout?",
      "Как requestAnimationFrame связан с rendering pipeline?",
      "Когда использовать requestIdleCallback?",
      "Как работает event propagation?",
      "Чем capture phase отличается от bubble phase?",
      "Что такое event delegation?",
      "Чем preventDefault отличается от stopPropagation?",
      "Что такое passive event listener?",
      "Как работают MutationObserver, ResizeObserver и IntersectionObserver?",
      "Чем localStorage отличается от sessionStorage?",
      "Когда использовать IndexedDB?",
      "Что такое Cache API?",
      "Как Service Worker перехватывает запросы?",
      "Какие стратегии offline-кэширования существуют?",
      "Что такое bfcache и что может помешать его использованию?",
      "Как History API используется SPA-роутером?",
      "Что такое Shadow DOM?",
      "Как custom elements связаны с Web Components?",
      "Какие ограничения накладывает same-origin policy?",
      "Что такое browser rendering sandbox?",
      "Как диагностировать memory leak через DevTools?",
    ],
  },
  {
    category: "Сеть и HTTP",
    level: "Middle",
    questions: [
      "Как работает DNS lookup?",
      "Чем TCP отличается от UDP?",
      "Как устанавливается TLS-соединение?",
      "Чем HTTP/1.1, HTTP/2 и HTTP/3 отличаются?",
      "Что такое head-of-line blocking?",
      "Что входит в HTTP request и response?",
      "Какие HTTP-методы считаются safe и idempotent?",
      "Чем PUT отличается от PATCH?",
      "Что означают основные группы HTTP status codes?",
      "Как работает content negotiation?",
      "Что такое CORS и почему это не механизм авторизации?",
      "Что вызывает CORS preflight?",
      "Что такое simple request?",
      "Как Cache-Control, ETag и Last-Modified управляют кэшем?",
      "Чем no-cache отличается от no-store?",
      "Что такое stale-while-revalidate?",
      "Как CDN выбирает cache key?",
      "Что такое cookie Domain, Path, Secure, HttpOnly и SameSite?",
      "Когда cookie лучше localStorage для токена?",
      "Как работает WebSocket handshake?",
      "SSE, WebSocket или polling: как выбрать?",
      "Что такое REST и какие ограничения он предполагает?",
      "Какие trade-offs у GraphQL?",
      "Как избежать request waterfall?",
      "Как спроектировать устойчивый клиент API?",
    ],
  },
  {
    category: "Безопасность",
    level: "Senior",
    questions: [
      "Что такое threat modeling и какие активы нужно защищать?",
      "Чем authentication отличается от authorization?",
      "Почему проверка прав только на frontend не защищает данные?",
      "Что такое Broken Access Control?",
      "Как предотвратить IDOR/BOLA?",
      "Какие ошибки относятся к Security Misconfiguration?",
      "Что такое software supply chain attack?",
      "Как lockfile, provenance и dependency scanning снижают supply-chain риск?",
      "Что такое XSS: stored, reflected и DOM-based?",
      "Какие browser sinks особенно опасны для DOM XSS?",
      "Почему экранирование зависит от контекста вывода?",
      "Как CSP и Trusted Types снижают риск XSS?",
      "Почему dangerouslySetInnerHTML требует особой осторожности?",
      "Что такое CSRF и какие условия нужны для атаки?",
      "Как SameSite cookie и CSRF token защищают от CSRF?",
      "Что такое SQL/NoSQL/command injection?",
      "Почему parameterized queries защищают от SQL injection?",
      "Что такое SSRF и может ли frontend участвовать в его эксплуатации?",
      "Что такое clickjacking и как от него защищаться?",
      "Что такое open redirect и почему он опасен?",
      "Какие данные нельзя хранить в localStorage?",
      "Как безопасно хранить refresh token?",
      "Что такое session fixation?",
      "Как реализовать rotation refresh-токенов и reuse detection?",
      "Какие риски несёт JWT и когда session cookie проще?",
      "Почему нельзя доверять claims JWT без проверки подписи?",
      "Как безопасно реализовать OAuth 2.0 Authorization Code + PKCE?",
      "Что такое WebAuthn/passkeys?",
      "Как защитить форму логина от credential stuffing?",
      "Что такое rate limiting и где его применять?",
      "Как корректно работать с пользовательскими файлами?",
      "Какие заголовки безопасности стоит настроить?",
      "Что защищают HSTS, X-Content-Type-Options и Referrer-Policy?",
      "Как избежать утечки секретов в frontend bundle и source maps?",
      "Почему переменные окружения frontend не являются секретами?",
      "Как логировать security-события без утечки персональных данных?",
      "Что означает fail secure при обработке исключений?",
      "Как безопасно показывать пользователю сообщения об ошибках?",
      "Что такое prototype pollution?",
      "Как проверить npm-пакет перед добавлением в проект?",
    ],
  },
  {
    category: "Тестирование",
    level: "Middle",
    questions: [
      "Чем unit, integration, component и E2E тесты отличаются?",
      "Что такое test pyramid и testing trophy?",
      "Что лучше тестировать: детали реализации или поведение?",
      "Когда mock оправдан, а когда делает тест бесполезным?",
      "Чем stub, spy, fake и mock отличаются?",
      "Как тестировать асинхронный код?",
      "Почему тест становится flaky?",
      "Как управлять временем и таймерами в тесте?",
      "Как тестировать React-компонент с точки зрения пользователя?",
      "Что стоит проверять accessibility-тестами?",
      "Когда snapshot test полезен?",
      "Почему большие snapshot-тесты часто игнорируют?",
      "Как тестировать hook?",
      "Как тестировать запросы без реального backend?",
      "Что такое contract testing?",
      "Как тестировать optimistic update и rollback?",
      "Как организовать test data builders?",
      "Как параллельность тестов может вызывать нестабильность?",
      "Что должно запускаться в CI на pull request?",
      "Как измерять полезное покрытие, а не гнаться за процентом?",
      "Как построить E2E-тест, устойчивый к изменению верстки?",
      "Как тестировать visual regression?",
    ],
  },
  {
    category: "Performance",
    level: "Senior",
    questions: [
      "Что измеряют LCP, INP и CLS?",
      "Чем lab data отличается от field data?",
      "Как найти LCP element и оптимизировать его загрузку?",
      "Какие причины высокого INP наиболее частые?",
      "Как разбить Long Task?",
      "Что такое Total Blocking Time и чем он отличается от INP?",
      "Как избежать layout shift?",
      "Что такое critical rendering path?",
      "Какие ресурсы являются render-blocking?",
      "Когда preload, preconnect и prefetch действительно полезны?",
      "Как приоритизировать hero image?",
      "Как выбрать стратегию загрузки шрифтов?",
      "Что такое code splitting по route и component?",
      "Как найти неиспользуемый JavaScript?",
      "Как tree shaking зависит от sideEffects?",
      "Почему большой hydration cost может испортить производительность?",
      "Что такое partial hydration и islands architecture?",
      "Как виртуализация снижает стоимость большого списка?",
      "Какие trade-offs имеет memoization?",
      "Как поставить и контролировать performance budget?",
      "Как Real User Monitoring дополняет synthetic monitoring?",
      "Как интерпретировать flame chart?",
      "Как CDN, compression и caching влияют на TTFB?",
      "Brotli или gzip: как выбрать?",
      "Как измерить эффект оптимизации и избежать ложного вывода?",
    ],
  },
  {
    category: "Архитектура frontend",
    level: "Senior",
    questions: [
      "Как разделить приложение на модули по бизнес-возможностям?",
      "Почему группировка только по типу файлов плохо масштабируется?",
      "Что такое dependency rule и как не допустить циклических зависимостей?",
      "Как определить границы shared-кода?",
      "Когда abstraction оправдана, а когда это premature generalization?",
      "Как спроектировать публичный API feature-модуля?",
      "Как выбрать между монолитом, monorepo и multirepo?",
      "Какие задачи решает monorepo toolchain?",
      "Как обеспечить независимые релизы пакетов?",
      "Когда микрофронтенды оправданы?",
      "Какие способы интеграции микрофронтендов существуют?",
      "Как синхронизировать routing, auth и design system между микрофронтендами?",
      "Какие риски создаёт Module Federation?",
      "Как построить дизайн-систему с устойчивым API?",
      "Как версионировать компоненты дизайн-системы?",
      "Как выполнить постепенную миграцию legacy-приложения?",
      "Что такое strangler pattern?",
      "Как оформить архитектурное решение в ADR?",
      "Как измерять стоимость технического долга?",
      "Где должны проходить error boundaries?",
      "Как спроектировать feature flags и безопасный rollout?",
      "Что такое observability на frontend?",
      "Какие данные должны содержать логи, метрики и traces?",
      "Как связать frontend error с backend trace?",
      "Как обеспечить обратную совместимость API?",
    ],
  },
  {
    category: "Frontend System Design",
    level: "Senior",
    questions: [
      "Как вы начинаете frontend system design interview?",
      "Какие функциональные и нефункциональные требования нужно уточнить?",
      "Как оценить масштаб: DAU, RPS, объём данных и медиа?",
      "Как спроектировать бесконечную ленту?",
      "Cursor pagination или offset pagination: как выбрать?",
      "Как сохранить scroll position и состояние при возврате в ленту?",
      "Как спроектировать поиск с autocomplete?",
      "Как избежать race conditions и лишних запросов в поиске?",
      "Как спроектировать чат с real-time сообщениями?",
      "Как обеспечить ordering, delivery status и optimistic messages?",
      "Как спроектировать collaborative editor?",
      "Как OT отличается от CRDT?",
      "Как спроектировать dashboard с десятками виджетов?",
      "Как кэшировать и обновлять данные виджетов независимо?",
      "Как спроектировать загрузку больших файлов?",
      "Как реализовать chunked/resumable upload?",
      "Как спроектировать offline-first приложение?",
      "Как разрешать конфликты после восстановления сети?",
      "Как спроектировать видеоплатформу на frontend?",
      "Как выбирать качество видео и адаптироваться к сети?",
      "Как спроектировать карту с тысячами объектов?",
      "Как кластеризовать и виртуализировать объекты карты?",
      "Как спроектировать checkout с защитой от двойной оплаты?",
      "Где нужна идемпотентность в пользовательском потоке?",
      "Как организовать normalized client cache?",
      "Как управлять cache invalidation после мутаций?",
      "Как обеспечить accessibility сложного продукта?",
      "Как заложить i18n, RTL и разные часовые пояса?",
      "Как защитить персональные данные на клиенте?",
      "Как спроектировать аналитику без деградации UX?",
      "Как определить границы SSR, CSR и edge rendering?",
      "Как обеспечить graceful degradation при частичном отказе API?",
      "Как выкатывать новый frontend без поломки старых вкладок?",
      "Как версионировать протокол между frontend и backend?",
      "Какие метрики подтвердят успех архитектурного решения?",
    ],
  },
  {
    category: "Алгоритмы и задачи",
    level: "Middle",
    questions: [
      "Как оценить временную и пространственную сложность алгоритма?",
      "Когда Map/Set улучшает сложность с O(n²) до O(n)?",
      "Как найти два числа с заданной суммой?",
      "Как проверить правильность скобочной последовательности?",
      "Как найти первый неповторяющийся символ?",
      "Как сгруппировать анаграммы?",
      "Как развернуть односвязный список?",
      "Как определить цикл в связном списке?",
      "Как выполнить обход дерева в глубину и ширину?",
      "Как найти максимальную глубину дерева?",
      "Как реализовать LRU cache?",
      "Как реализовать очередь через два стека?",
      "Как найти пересечение двух массивов?",
      "Как удалить дубликаты без потери порядка?",
      "Как реализовать binary search и избежать off-by-one?",
      "Как объединить пересекающиеся интервалы?",
      "Как работает sliding window?",
      "Как найти самую длинную подстроку без повторов?",
      "Как реализовать debounce с cancel и flush?",
      "Как реализовать Promise.all?",
      "Как реализовать ограничитель конкурентности промисов?",
      "Как глубоко сравнить два значения с учётом циклов?",
      "Как преобразовать плоский список с parentId в дерево?",
      "Как реализовать EventEmitter?",
      "Как написать immutable update по строковому пути?",
    ],
  },
  {
    category: "Инженерные и поведенческие",
    level: "Senior",
    questions: [
      "Расскажите о самом сложном техническом решении и его trade-offs.",
      "Как вы разбираетесь с задачей, требования которой неясны?",
      "Приведите пример ошибки в production и ваших действий.",
      "Как вы проводите root cause analysis?",
      "Расскажите о конфликте с коллегой по техническому решению.",
      "Как вы даёте и принимаете code review feedback?",
      "Как вы убеждаете команду инвестировать в технический долг?",
      "Приведите пример, когда вы отказались от красивого технического решения.",
      "Как вы оцениваете задачу с высокой неопределённостью?",
      "Как разбить большой проект на безопасные этапы?",
      "Как вы балансируете скорость, качество и scope?",
      "Как определить, что рефакторинг успешен?",
      "Как вы менторите менее опытных разработчиков?",
      "Как вы действуете, если не согласны с решением руководителя?",
      "Приведите пример инициативы, повлиявшей на продуктовые метрики.",
      "Как вы измеряете личный инженерный результат?",
      "Как организовать техническое лидерство без формальной власти?",
      "Что вы делаете в первые 30 минут production-инцидента?",
      "Как вы документируете важные решения?",
      "Как вы учитесь новой технологии и проверяете глубину понимания?",
    ],
  },
  {
    category: "React: современный",
    level: "Senior",
    questions: [
      "Что такое Actions в React 19 и какую модель мутаций они предлагают?",
      "Как работает useActionState и что входит в возвращаемый tuple?",
      "Когда использовать useOptimistic и как обрабатывать rollback?",
      "Как useFormStatus получает pending-состояние родительской формы?",
      "Что изменилось в работе ref как prop в React 19?",
      "Как React Compiler автоматически мемоизирует компоненты и значения?",
      "Какие правила чистоты необходимы для корректной работы React Compiler?",
      "Когда директивы use memo и use no memo действительно нужны?",
      "Чем Server Component отличается от SSR-компонента?",
      "Почему для Server Components нет директивы use server?",
      "Что такое Server Function и как она пересекает network boundary?",
      "Какие значения можно сериализовать между Server и Client Components?",
      "Как избежать server-client waterfall в дереве Server Components?",
      "Как Suspense участвует в streaming server rendering?",
      "Что такое selective hydration?",
      "Как React обрабатывает события до завершения hydration?",
      "Какие задачи решает компонент Activity?",
      "Как use() работает с Promise и Context?",
      "Чем use() отличается от обычных хуков по правилам вызова?",
      "Как спроектировать Error Boundary для route, widget и mutation?",
      "Почему Error Boundary не ловит ошибки event handler автоматически?",
      "Как избежать tearing при concurrent rendering?",
      "Что гарантирует useSyncExternalStore для внешнего состояния?",
      "Как измерять пользу memoization после включения React Compiler?",
      "Как организовать abort и cleanup при переходах между экранами?",
      "Как корректно реализовать optimistic очередь нескольких мутаций?",
      "Как тестировать transition, Suspense и optimistic UI?",
      "Как построить accessible streaming-интерфейс без скачков фокуса?",
      "Как мигрировать большое приложение с ручной мемоизации на Compiler?",
      "Какие границы React являются framework-specific, а какие стабильными API?",
    ],
  },
  {
    category: "Redux и Redux Toolkit",
    level: "Middle",
    questions: [
      "Какие три принципа лежат в основе Redux?",
      "Когда Redux оправдан, а когда достаточно локального state или Context?",
      "Что такое store, action, reducer и dispatch?",
      "Почему reducer обязан быть чистым?",
      "Как однонаправленный поток данных упрощает отладку?",
      "Почему Redux Toolkit является рекомендуемым способом писать Redux?",
      "Что делает configureStore?",
      "Как createSlice генерирует reducer и action creators?",
      "Почему в createSlice можно писать внешне мутирующий код?",
      "Как Immer создаёт immutable update и какие у него ограничения?",
      "Что такое draft state и почему нельзя возвращать draft наружу?",
      "Как правильно типизировать RootState, AppDispatch и typed hooks?",
      "Как выбирать структуру Redux state?",
      "Почему derived data не стоит хранить в store?",
      "Что такое selector и зачем нужен Reselect?",
      "Как работает memoization createSelector?",
      "Почему selector может пересчитываться чаще ожидаемого?",
      "Как стабилизировать selector с параметрами?",
      "Когда нормализовать данные в Redux?",
      "Что делает createEntityAdapter?",
      "Чем createAsyncThunk отличается от обычного thunk?",
      "Как обрабатывать pending, fulfilled и rejected createAsyncThunk?",
      "Как отменить createAsyncThunk через AbortSignal?",
      "RTK Query или createAsyncThunk: как выбрать?",
      "Как RTK Query формирует cache key?",
      "Как работают providesTags и invalidatesTags?",
      "Что означают keepUnusedDataFor и refetchOnMountOrArgChange?",
      "Как выполнить optimistic update в RTK Query?",
      "Как откатить optimistic patch после ошибки?",
      "Как работают onQueryStarted и onCacheEntryAdded?",
      "Как реализовать polling и refetch on focus/reconnect?",
      "Как разделить один API slice по feature-модулям?",
      "Почему обычно рекомендуется один API slice на base URL?",
      "Как listener middleware реагирует на actions и state changes?",
      "Когда listener middleware лучше thunk, saga или observable?",
      "Как listenerApi.cancelActiveListeners реализует takeLatest?",
      "Как написать custom middleware и сохранить return value next(action)?",
      "Почему middleware нельзя бездумно вызывать dispatch до next?",
      "Как DevTools time travel зависит от serializable state и actions?",
      "Какие значения не стоит хранить в Redux state?",
      "Как настроить serializableCheck для осознанных исключений?",
      "Как избежать лишних React renders с useSelector?",
      "Как equalityFn влияет на useSelector?",
      "Почему новый объект из selector вызывает render?",
      "Как внедрять Redux store при SSR без утечки между запросами?",
      "Как гидратировать Redux state безопасно?",
      "Как тестировать reducer, selector, thunk и RTK Query endpoint?",
      "Как постепенно мигрировать legacy Redux на Redux Toolkit?",
      "Когда Redux Saga всё ещё может быть оправдана?",
      "Как организовать boundaries между domain state и server cache?",
    ],
  },
  {
    category: "Vue: advanced",
    level: "Senior",
    questions: [
      "Как track и trigger устроены в реактивной системе Vue?",
      "Какие ограничения реактивности решает Proxy по сравнению с Object.defineProperty?",
      "Чем shallowRef, shallowReactive и markRaw отличаются?",
      "Когда использовать triggerRef?",
      "Как customRef позволяет управлять tracking и triggering?",
      "Как effectScope помогает управлять жизненным циклом composable?",
      "Что делают onScopeDispose и getCurrentScope?",
      "Как устроена очередь обновлений Vue и nextTick?",
      "Когда flush: pre, post и sync нужны в watcher?",
      "Как cleanup watcher предотвращает race condition?",
      "Чем eager и lazy computed отличаются концептуально?",
      "Как computed stability влияет на обновления потомков?",
      "Как избежать потери реактивности при destructuring props?",
      "Что делают toRef, toRefs и toValue?",
      "Как defineModel компилируется в prop и emit?",
      "Как типизировать generic Vue-компонент?",
      "Как типизировать provide/inject через InjectionKey?",
      "Как Teleport влияет на DOM, ownership и события?",
      "Как KeepAlive кэширует экземпляры компонентов?",
      "Как include, exclude и max управляют KeepAlive?",
      "Как Suspense координирует async setup и async components?",
      "Как hydration strategy выбирается для async component?",
      "Какие причины SSR hydration mismatch характерны для Vue?",
      "Как избежать cross-request state pollution при Vue SSR?",
      "Как безопасно сериализовать Pinia state в HTML?",
      "Как устроены Pinia setup stores и option stores?",
      "Как actions и getters Pinia взаимодействуют с TypeScript?",
      "Как подписки $subscribe и $onAction применяются на практике?",
      "Как тестировать composables, Pinia stores и async components?",
      "Когда render function или JSX лучше template?",
    ],
  },
  {
    category: "Angular: advanced",
    level: "Senior",
    questions: [
      "Как Angular строит иерархию EnvironmentInjector и ElementInjector?",
      "Чем provider scopes root, platform и component отличаются?",
      "Как InjectionToken помогает типизировать не-классовые зависимости?",
      "Что такое multi provider и где он применяется?",
      "Как assertInInjectionContext помогает библиотечному API?",
      "Как signal graph определяет producer и consumer?",
      "Почему зависимости computed signal являются динамическими?",
      "Как equality function влияет на signal updates?",
      "Когда использовать untracked?",
      "Чем linkedSignal отличается от computed и writable signal?",
      "Как resource моделирует асинхронные данные?",
      "Как rxResource связывает signals и RxJS?",
      "Как toSignal и toObservable управляют subscription lifecycle?",
      "Какие уведомления запускают change detection в zoneless Angular?",
      "Как мигрировать приложение с Zone.js на zoneless?",
      "Чем afterNextRender и afterEveryRender отличаются от lifecycle hooks?",
      "Как afterRenderEffect работает с DOM side effects?",
      "Как новый control flow @if, @for и @switch компилируется?",
      "Зачем @for требует track expression?",
      "Как deferrable views через @defer уменьшают initial bundle?",
      "Какие trigger у @defer существуют и как выбрать placeholder?",
      "Как standalone APIs изменили устройство Angular-приложения?",
      "Как functional guards и interceptors используют inject?",
      "Как typed reactive forms моделируют nullability?",
      "Как Signal Forms отличаются от Reactive Forms?",
      "Как Angular SSR выбирает server, prerender и client rendering?",
      "Что такое incremental hydration?",
      "Как event replay работает до hydration?",
      "Почему TransferState может привести к утечке персональных данных?",
      "Как Angular sanitization и Trusted Types защищают template?",
      "Когда DomSanitizer.bypassSecurityTrust опасен?",
      "Как настроить lazy routes и preloading strategy?",
      "Как диагностировать нестабильность Angular SSR?",
      "Как профилировать change detection и signal graph?",
      "Как тестировать signal-based component без лишнего detectChanges?",
    ],
  },
  {
    category: "Nuxt",
    level: "Junior",
    questions: [
      "Что такое Nuxt и какие задачи он решает поверх Vue?",
      "Как устроена файловая маршрутизация в Nuxt?",
      "Чем layouts отличаются от pages и components?",
      "Как работают auto-imports компонентов и composables?",
      "Для чего используется NuxtLink?",
      "Чем useFetch отличается от обычного fetch?",
      "Что такое runtimeConfig и чем public-конфигурация отличается от private?",
      "Как добавить глобальные стили и assets в Nuxt?",
      "Как работают plugins в Nuxt?",
      "Для чего нужны middleware маршрутов?",
      "Как задавать title и meta-теги через useHead и useSeoMeta?",
      "Чем папки public и assets отличаются друг от друга?",
    ],
  },
  {
    category: "Nuxt",
    level: "Middle",
    questions: [
      "Чем SSR, CSR, SSG и hybrid rendering в Nuxt отличаются?",
      "Как useAsyncData дедуплицирует запросы и передаёт payload при hydration?",
      "Когда использовать useFetch, useAsyncData и $fetch?",
      "Почему повторный запрос может выполниться и на сервере, и на клиенте?",
      "Как работают route rules и selective rendering?",
      "Что такое Nitro и какую роль он играет в Nuxt?",
      "Как создавать server routes и API handlers в Nuxt?",
      "Как безопасно читать cookies и headers при SSR?",
      "Как избежать hydration mismatch в Nuxt-приложении?",
      "Как организовать authentication и route middleware без мигания интерфейса?",
      "Как управлять глобальным состоянием через useState и Pinia при SSR?",
      "Как подключать client-only библиотеки, которые обращаются к window?",
    ],
  },
  {
    category: "Nuxt",
    level: "Senior",
    questions: [
      "Как Nuxt формирует server payload и восстанавливает состояние при hydration?",
      "Как избежать cross-request state pollution в Nuxt SSR?",
      "Как работает кэширование Nitro: cachedEventHandler и cachedFunction?",
      "Как проектировать invalidation кэша при hybrid rendering?",
      "Как islands и selective hydration уменьшают стоимость JavaScript?",
      "Как оптимизировать Nuxt-приложение по LCP, INP и размеру client bundle?",
      "Как диагностировать ошибки, возникающие только в SSR или edge runtime?",
      "Как написать собственный Nuxt module и когда он оправдан?",
      "Как hooks и modules участвуют в lifecycle сборки Nuxt?",
      "Как развернуть Nuxt на Node, serverless и edge и какие есть ограничения?",
      "Как обеспечить observability server routes и SSR Nuxt?",
      "Как безопасно сериализовать пользовательские данные в Nuxt payload?",
    ],
  },
  {
    category: "NestJS",
    level: "Junior",
    questions: [
      "Что такое NestJS и какую архитектуру он предлагает?",
      "Чем module, controller и provider отличаются друг от друга?",
      "Как работает dependency injection в NestJS?",
      "Для чего нужен декоратор Injectable?",
      "Как зарегистрировать provider в module?",
      "Как создать REST endpoint через controller?",
      "Как получать params, query и body запроса?",
      "Что такое DTO и зачем он нужен?",
      "Как ValidationPipe проверяет входные данные?",
      "Чем middleware отличается от guard?",
      "Как обрабатывать ошибки через built-in HTTP exceptions?",
      "Как использовать ConfigModule для переменных окружения?",
    ],
  },
  {
    category: "NestJS",
    level: "Middle",
    questions: [
      "В каком порядке выполняются middleware, guards, interceptors, pipes и exception filters?",
      "Чем useClass, useValue, useFactory и useExisting providers отличаются?",
      "Как работают provider scopes singleton, request и transient?",
      "Когда использовать guard, а когда interceptor или pipe?",
      "Как создать собственный decorator с метаданными?",
      "Как Reflector используется в authorization guard?",
      "Как реализовать JWT-аутентификацию через Passport?",
      "Как организовать role-based и permission-based authorization?",
      "Как подключать TypeORM, Prisma или Mongoose в NestJS?",
      "Как управлять транзакциями и unit of work?",
      "Как тестировать controller и provider через TestingModule?",
      "Как документировать API через Swagger/OpenAPI?",
    ],
  },
  {
    category: "NestJS",
    level: "Senior",
    questions: [
      "Как устроен dependency-injection container NestJS и разрешение circular dependencies?",
      "Почему forwardRef является компромиссом и как убрать циклические зависимости?",
      "Как проектировать dynamic modules с forRoot и forRootAsync?",
      "Как построить модульный monolith на NestJS с явными domain boundaries?",
      "Как применять CQRS и event-driven architecture в NestJS?",
      "Как обеспечить idempotency команд и обработчиков сообщений?",
      "Как NestJS работает с microservices transports и delivery semantics?",
      "Как реализовать distributed tracing и correlation ID?",
      "Как настроить graceful shutdown и корректно закрыть ресурсы?",
      "Как защищать NestJS API от mass assignment, injection и broken access control?",
      "Как диагностировать утечки памяти и деградацию event loop в NestJS?",
      "Как организовать contract, integration и end-to-end тесты большого NestJS-приложения?",
    ],
  },
  {
    category: "Рендеринг: CSR, SSR, SSG и ISR",
    level: "Junior",
    questions: [
      "Что такое Client-Side Rendering и как загружается CSR-приложение?",
      "Что такое Server-Side Rendering и когда HTML создаётся на сервере?",
      "Что такое Static Site Generation и когда страницы создаются при SSG?",
      "Что такое Incremental Static Regeneration и чем ISR отличается от SSG?",
      "Чем SSR, SSG и CSR отличаются по SEO, скорости и стоимости инфраструктуры?",
      "Что такое prerendering и какие страницы выгодно генерировать заранее?",
      "Что такое hydration после серверного рендеринга?",
      "Почему готовый HTML ещё не означает, что страница интерактивна?",
      "Как CDN помогает статически сгенерированному сайту?",
      "Как выбрать rendering strategy для лендинга, личного кабинета и новостной страницы?",
      "Какие данные нельзя безопасно встроить в статическую страницу?",
      "Что происходит при переходе между страницами после первой загрузки SSR-приложения?",
    ],
  },
  {
    category: "Рендеринг: CSR, SSR, SSG и ISR",
    level: "Middle",
    questions: [
      "Как выглядит полный lifecycle SSR-запроса от HTTP request до hydration?",
      "Из-за чего возникает hydration mismatch и как его диагностировать?",
      "Как безопасно сериализовать server state в HTML?",
      "Что такое streaming SSR и чем он отличается от обычного SSR?",
      "Как Suspense boundaries позволяют постепенно отправлять HTML?",
      "Как устроена revalidation в ISR и что видит пользователь во время обновления?",
      "Чем time-based revalidation отличается от on-demand revalidation?",
      "Как cache-control, s-maxage и stale-while-revalidate связаны с SSR?",
      "Как персонализация и авторизация влияют на выбор SSR, SSG или CSR?",
      "Когда edge rendering полезнее традиционного Node.js SSR?",
      "Как избежать повторной загрузки данных после hydration?",
      "Как fallback-страницы работают для динамических маршрутов, отсутствующих во время build?",
    ],
  },
  {
    category: "Рендеринг: CSR, SSR, SSG и ISR",
    level: "Senior",
    questions: [
      "Как выбрать rendering strategy отдельно для каждого маршрута большого приложения?",
      "Что такое Partial Prerendering и как оно сочетает статический shell с динамическими участками?",
      "Чем React Server Components отличаются от SSR и SSG?",
      "Как islands architecture и selective hydration уменьшают объём клиентского JavaScript?",
      "Как спроектировать cache key для SSR-страницы с локалью, экспериментами и авторизацией?",
      "Как предотвратить cache stampede при массовой revalidation?",
      "Как организовать invalidation зависимых страниц после изменения контента?",
      "Почему module-level singleton может смешать данные пользователей при SSR?",
      "Какие XSS-риски возникают при встраивании сериализованного состояния в HTML?",
      "Как измерять TTFB, LCP, hydration cost и server render time раздельно?",
      "Как проектировать graceful degradation при отказе SSR backend или data source?",
      "Какие trade-offs появляются при переносе SSR на edge runtime?",
    ],
  },
  {
    category: "Node.js: основы",
    level: "Junior",
    questions: [
      "Что такое Node.js и чем runtime отличается от языка JavaScript?",
      "Чем выполнение JavaScript в Node.js отличается от браузера?",
      "Какую роль играют V8 и libuv в Node.js?",
      "Что такое объект process и какие данные через него доступны?",
      "Для чего используются переменные окружения process.env?",
      "Чем CommonJS отличается от ES Modules в Node.js?",
      "Как работают require, module.exports, import и export?",
      "Для чего нужен package.json и какие его поля наиболее важны?",
      "Чем dependencies отличаются от devDependencies?",
      "Зачем нужен package-lock.json и следует ли добавлять его в Git?",
      "Как работает semantic versioning и что означают ^ и ~ в версиях пакетов?",
      "Как создавать и запускать npm scripts?",
      "Чем npx отличается от npm run и глобальной установки пакета?",
      "Как модули path и URL помогают работать с путями к файлам?",
      "Как читать и записывать файлы через модуль fs?",
      "Чем синхронные методы fs отличаются от асинхронных?",
      "Что такое Buffer и когда он нужен?",
      "Что такое streams и какие виды потоков есть в Node.js?",
      "Зачем нужен pipe и как он связан с backpressure?",
      "Что такое EventEmitter и как работают on, once и emit?",
      "Как Event Loop работает в Node.js на базовом уровне?",
      "Почему тяжёлое синхронное вычисление блокирует все запросы?",
      "Как использовать callbacks, Promise и async/await в Node.js?",
      "Как правильно обрабатывать ошибки в async-функциях?",
      "Что такое unhandled rejection и почему её нельзя игнорировать?",
      "Как создать простой HTTP-сервер стандартным модулем node:http?",
      "Что содержат объекты request и response в Node.js HTTP-сервере?",
      "Как устанавливать status code и HTTP headers в ответе?",
      "Как корректно завершать Node.js-приложение по SIGTERM и SIGINT?",
      "Чем worker_threads отличаются от child_process и когда они нужны?",
    ],
  },
  {
    category: "Интернет и протоколы: advanced",
    level: "Senior",
    questions: [
      "Как пакет проходит от браузера через домашний роутер, ISP и автономные системы до сервера?",
      "Что такое IP-адрес, subnet, default gateway и NAT?",
      "Чем IPv4 отличается от IPv6 и зачем нужен dual stack?",
      "Как рекурсивный DNS resolver находит authoritative name server?",
      "Как DNS-кэширование, TTL и negative caching влияют на обновление домена?",
      "Чем A, AAAA, CNAME, NS, MX и TXT DNS-записи отличаются?",
      "Что такое DNS over HTTPS и DNS over TLS и какие trade-offs они создают?",
      "Как Anycast направляет пользователя к ближайшей точке присутствия?",
      "Как устроен TCP three-way handshake?",
      "Как sequence number, acknowledgement и retransmission обеспечивают надёжность TCP?",
      "Что такое TCP flow control и чем он отличается от congestion control?",
      "Как slow start, congestion window и packet loss влияют на скорость загрузки?",
      "Что такое Nagle algorithm и когда TCP_NODELAY полезен?",
      "Что такое TCP keepalive и чем он отличается от application heartbeat?",
      "Почему потеря TCP-пакета создаёт head-of-line blocking для HTTP/2?",
      "Как QUIC объединяет transport security и мультиплексирование потоков?",
      "Почему HTTP/3 меньше страдает от head-of-line blocking?",
      "Что происходит при смене сети благодаря QUIC connection migration?",
      "Как браузер проверяет цепочку TLS-сертификатов?",
      "Что происходит во время TLS 1.3 handshake?",
      "Как SNI и ALPN участвуют в установлении HTTPS-соединения?",
      "Что такое TLS session resumption и 0-RTT?",
      "Какие риски replay появляются у TLS 0-RTT?",
      "Что такое HSTS и как он предотвращает downgrade к HTTP?",
      "Что такое certificate pinning и почему его сложно безопасно поддерживать?",
      "Где обычно завершается TLS при использовании CDN или load balancer?",
      "Чем forward proxy отличается от reverse proxy?",
      "Какие задачи решают reverse proxy, load balancer и API gateway?",
      "Чем L4-балансировка отличается от L7-балансировки?",
      "Как sticky sessions влияют на масштабирование и отказоустойчивость?",
      "Как health checks и connection draining помогают безопасному деплою?",
      "Как CDN выбирает ближайший PoP и когда обращается к origin?",
      "Что такое cache hit, cache miss, cache fill и origin shield?",
      "Как спроектировать CDN cache key с query, headers, cookies и encoding?",
      "Как purge, cache tags и versioned URLs решают invalidation CDN-кэша?",
      "Как защититься от cache poisoning и утечки приватных данных через CDN?",
      "Как Vary влияет на HTTP-кэш и почему может снизить hit ratio?",
      "Как Range Requests и статус 206 используются для видео и больших файлов?",
      "Как WebSocket upgrade переводит HTTP-соединение в двунаправленный протокол?",
      "Как устроены WebSocket frames, masking и fragmentation?",
      "Для чего WebSocket использует ping/pong и application heartbeat?",
      "Как проектировать reconnect с exponential backoff и jitter?",
      "Как обеспечить ordering, deduplication и delivery acknowledgement сообщений?",
      "Как backpressure проявляется в WebSocket-клиенте и сервере?",
      "Как масштабировать WebSocket через несколько серверов и общий pub/sub?",
      "Какие проблемы sticky sessions создают для WebSocket-кластера?",
      "Как SSE использует event stream, retry и Last-Event-ID?",
      "Когда выбрать WebSocket, SSE, long polling или обычный polling?",
    ],
  },
];

export const interviewQuestions: InterviewQuestion[] = groups.flatMap((group, groupIndex) =>
  group.questions.map((question, questionIndex) => ({
    id: `q-${groupIndex + 1}-${questionIndex + 1}`,
    category: group.category,
    level: group.level,
    question,
  })),
);

export const questionCategories = [...new Set(groups.map((group) => group.category))];
